"""
L2 Context Inspector — PR-20
=============================

Dumps the full LLM input (system prompt + conversation history + slot state)
for any call_sid + turn_number from the database, as a readable text file.

Usage:
    python -m server.brain.context_inspector <call_sid> <turn_number> [output_file]

Example:
    python -m server.brain.context_inspector demo-7bba699665ed 2 /tmp/t2_context.txt
    cat /tmp/t2_context.txt

This answers "what exactly did the LLM see in turn N?" in ~5 seconds instead of
30 minutes of code reading. Essential for verifying PR-16b (is get_menu in context?),
diagnosing self-contradiction bugs (T2→T8), and auditing system prompt rendering.
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
import textwrap
from datetime import timezone
from typing import Optional


# ---------------------------------------------------------------------------
# DB helpers
# ---------------------------------------------------------------------------

async def _fetch_turns(call_sid: str, max_turn: int) -> list[dict]:
    """Fetch all turns up to max_turn for call_sid from google_turn_metrics."""
    import asyncpg  # type: ignore

    db_url = os.environ.get("DATABASE_URL", "postgresql://sailly:sailly@localhost/sailly")
    conn = await asyncpg.connect(db_url)
    try:
        rows = await conn.fetch(
            """
            SELECT turn_number, user_text, bot_text, tools_called,
                   slot_state_json, tts_situation, tts_mood,
                   prompt_tokens_in, prompt_tokens_out,
                   stt_latency_ms, llm_latency_ms, total_latency_ms,
                   created_at
            FROM google_turn_metrics
            WHERE call_sid = $1
            ORDER BY turn_number
            """,
            call_sid,
        )
        return [dict(r) for r in rows if r["turn_number"] <= max_turn]
    finally:
        await conn.close()


# ---------------------------------------------------------------------------
# Prompt reconstruction
# ---------------------------------------------------------------------------

def _try_render_system_prompt(tenant_id: str = "doboo") -> str:
    """Attempt to render the L2 system prompt for a tenant."""
    try:
        from server.brain.tier2_runner import Tier2AudioRunner
        runner = Tier2AudioRunner.__new__(Tier2AudioRunner)
        runner.tenant_id = tenant_id
        runner.gemini_model = "gemini-2.5-flash"
        runner.temperature = 0.2
        runner._active_prompt_override = None
        runner._fast_model = ""
        runner._fast_nodes = set()
        runner.audio_injector = None
        runner.llm_client = None
        runner.tts_client = None
        runner.cost_tracker = None
        runner.scorer = None
        runner._last_stream_usage_metadata = None
        return runner._build_tier2_prompt()
    except Exception as exc:
        return f"[could not render tier2 prompt: {exc}]"


def _build_history_section(turns: list[dict], target_turn: int) -> str:
    """Build the conversation history as the LLM would receive it."""
    lines = []
    for t in turns:
        tn = t["turn_number"]
        if tn >= target_turn:
            break
        user = (t.get("user_text") or "").strip()
        bot = (t.get("bot_text") or "").strip()
        if user:
            lines.append(f"  [Turn {tn}] USER:  {user}")
        if bot:
            lines.append(f"  [Turn {tn}] MODEL: {bot}")
    return "\n".join(lines) if lines else "  (no prior turns)"


def _slot_state_summary(slot_json) -> str:
    if not slot_json:
        return "  (no slot state)"
    if isinstance(slot_json, str):
        try:
            slot_json = json.loads(slot_json)
        except Exception:
            return f"  {slot_json}"
    lines = []
    for k, v in (slot_json or {}).items():
        if isinstance(v, dict):
            val = v.get("value")
            status = v.get("status", "?")
            conf = v.get("confidence", "?")
            if val is not None:
                lines.append(f"  {k}: {val!r}  [{status}, conf={conf}]")
            else:
                lines.append(f"  {k}: (missing)  [{status}]")
        else:
            lines.append(f"  {k}: {v!r}")
    return "\n".join(lines) if lines else "  (empty)"


# ---------------------------------------------------------------------------
# Main output builder
# ---------------------------------------------------------------------------

def build_report(call_sid: str, target_turn: int, turns: list[dict]) -> str:
    target = next((t for t in turns if t["turn_number"] == target_turn), None)

    header = f"""
╔══════════════════════════════════════════════════════════════════════════════════╗
║  L2 CONTEXT INSPECTOR — call_sid={call_sid}  turn={target_turn}
╚══════════════════════════════════════════════════════════════════════════════════╝
Generated by: server.brain.context_inspector (PR-20)
""".strip()

    # ── Turn metadata ────────────────────────────────────────────────────────
    if target:
        ts = target.get("created_at")
        meta = f"""
=== TURN {target_turn} METADATA ===
  Timestamp:        {ts}
  user_text:        {(target.get('user_text') or '').strip()!r}
  bot_text (DB):    {(target.get('bot_text') or '').strip()!r}
  tools_called:     {target.get('tools_called')}
  tts_situation:    {target.get('tts_situation')}
  tts_mood:         {target.get('tts_mood')}
  stt_latency_ms:   {target.get('stt_latency_ms')}
  llm_latency_ms:   {target.get('llm_latency_ms')}
  total_latency_ms: {target.get('total_latency_ms')}
  prompt_tokens_in: {target.get('prompt_tokens_in')}
  prompt_tokens_out:{target.get('prompt_tokens_out')}
""".strip()
    else:
        meta = f"=== TURN {target_turn} METADATA ===\n  (turn not found in DB)"

    # ── Conversation history ─────────────────────────────────────────────────
    history = f"""
=== CONVERSATION HISTORY (sent to LLM as 'contents') ===
  (turns 1 through {target_turn - 1}, role:user + role:model pairs)

{_build_history_section(turns, target_turn)}
""".strip()

    # ── Slot state ───────────────────────────────────────────────────────────
    slot_data = target.get("slot_state_json") if target else None
    slots_section = f"""
=== SLOT STATE AT TURN {target_turn} ENTRY ===
{_slot_state_summary(slot_data)}
""".strip()

    # ── System prompt ────────────────────────────────────────────────────────
    # Determine tenant from call_sid prefix; default to doboo
    tenant_id = "doboo"
    system_prompt = _try_render_system_prompt(tenant_id)
    sys_section = f"""
=== SYSTEM PROMPT (tier2_runner._build_tier2_prompt, tenant={tenant_id}) ===
  NOTE: In production this may be overridden by MemoryManager.build_context (L1-L8).
  The actual override is NOT reconstructable from DB alone — use live debug logging
  to capture the exact context string. This rendering shows the base tier2 prompt.

{textwrap.indent(system_prompt, '  ')}
""".strip()

    # ── Tools in prior turns ─────────────────────────────────────────────────
    tool_history = []
    for t in turns:
        if t["turn_number"] >= target_turn:
            break
        tools = t.get("tools_called")
        if isinstance(tools, str):
            try:
                tools = json.loads(tools)
            except Exception:
                pass
        if tools:
            tool_history.append(f"  Turn {t['turn_number']}: {tools}")
    tool_sec = "=== TOOLS CALLED IN PRIOR TURNS ===\n" + (
        "\n".join(tool_history) if tool_history else "  (none)"
    )

    # ── Answer to common questions ───────────────────────────────────────────
    qa_lines = [
        "=== QUICK ANSWERS ===",
    ]
    # Was get_menu called before this turn?
    get_menu_turn = next(
        (
            t["turn_number"]
            for t in turns
            if t["turn_number"] < target_turn
            and "get_menu" in (t.get("tools_called") or [])
        ),
        None,
    )
    if get_menu_turn:
        qa_lines.append(
            f"  get_menu called in turn {get_menu_turn} — menu data was available in LLM context"
            f" (injected as tool result in build_history() for turns after T{get_menu_turn})."
        )
    else:
        qa_lines.append(
            f"  get_menu NOT called before turn {target_turn} — no menu data in context."
        )

    # Was ai_greeting called before this turn?
    ai_greeting_turn = next(
        (
            t["turn_number"]
            for t in turns
            if t["turn_number"] < target_turn
            and "ai_greeting" in (t.get("tools_called") or [])
        ),
        None,
    )
    if ai_greeting_turn:
        qa_lines.append(
            f"  ai_greeting called in turn {ai_greeting_turn} — state.ai_greeting_called=True."
        )
    qa_sec = "\n".join(qa_lines)

    return "\n\n".join([header, meta, history, slots_section, tool_sec, qa_sec, sys_section])


# ---------------------------------------------------------------------------
# CLI entrypoint
# ---------------------------------------------------------------------------

async def _main(call_sid: str, turn_number: int, output_path: Optional[str]) -> None:
    print(f"Fetching turns for {call_sid} up to turn {turn_number}...")
    turns = await _fetch_turns(call_sid, turn_number)
    print(f"  Found {len(turns)} turns.")

    report = build_report(call_sid, turn_number, turns)

    if output_path:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(report)
        print(f"  Written to: {output_path}")
    else:
        print(report)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python -m server.brain.context_inspector <call_sid> <turn_number> [output_file]")
        sys.exit(1)

    _call_sid = sys.argv[1]
    _turn = int(sys.argv[2])
    _out = sys.argv[3] if len(sys.argv) > 3 else None

    asyncio.run(_main(_call_sid, _turn, _out))
