import { SessionRow, TurnRow, Layer1Decision, Layer3Changes } from '@/types/sailly-debugger';

// Mock fixture: happy path call
const fixtureHappyPath: TurnRow[] = [
  {
    id: 1,
    call_id: 'test-call-1',
    call_sid: 'test-call-1-sid',
    tenant_id: 'doboo',
    turn_number: 1,
    user_text: 'Hallo, ich möchte einen Tisch reservieren',
    bot_text: 'Willkommen! Ich helfe dir gerne eine Reservation zu buchen.',
    vad_start_ms: 100,
    vad_stop_ms: 2500,
    stt_confidence: 0.95,
    stt_latency_ms: 200,
    llm_latency_ms: 500,
    tts_latency_ms: 1200,
    tts_ttfb_ms: 300,
    total_latency_ms: 2000,
    acoustic_gap_ms: 50,
    tools_called: [],
    node_name: 'GREETING',
    layer1_decision: {
      node: 'GREETING',
      forced_tools: [],
      state_hash: 'hash_1',
      validators_run: [],
    },
    layer2_raw_output: 'greeting_response',
    layer3_changes: {
      warnings: [],
      text_changed: false,
      tools_changed: false,
    },
    stage1_clean_text: 'Hello, I want to book a table',
    stage2_clean_text: 'Hello, I want to book a table',
    stage3_text: 'Welcome! I will help you book a reservation.',
    has_markdown: false,
    has_greeting: true,
    tts_situation: 'normal',
    tts_mood: 'friendly',
    tts_suppressed_reason: null,
    validation_breakdown: {},
    build_sha: 'abc1234',
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    call_id: 'test-call-1',
    call_sid: 'test-call-1-sid',
    tenant_id: 'doboo',
    turn_number: 2,
    user_text: 'Für 4 Personen, morgen um 19 Uhr',
    bot_text: 'Perfekt! 4 Personen morgen um 19:00 Uhr. Kann ich deine Telefonnummer haben?',
    vad_start_ms: 2600,
    vad_stop_ms: 5100,
    stt_confidence: 0.92,
    stt_latency_ms: 180,
    llm_latency_ms: 550,
    tts_latency_ms: 1400,
    tts_ttfb_ms: 280,
    total_latency_ms: 2200,
    acoustic_gap_ms: 40,
    tools_called: ['check_availability'],
    node_name: 'ORDER_OR_RESERVE',
    layer1_decision: {
      node: 'ORDER_OR_RESERVE',
      forced_tools: ['check_availability'],
      state_hash: 'hash_2',
      validators_run: [
        {
          slot: 'date',
          status: 'verified',
          duration_ms: 50,
          retry: 0,
        },
        {
          slot: 'party_size',
          status: 'verified',
          duration_ms: 30,
          retry: 0,
        },
      ],
    },
    layer2_raw_output: 'reservation_slot_extract',
    layer3_changes: {
      warnings: [],
      text_changed: false,
      tools_changed: false,
    },
    stage1_clean_text: 'For 4 people, tomorrow at 7 pm',
    stage2_clean_text: 'For 4 people, tomorrow at 19:00',
    stage3_text: 'Perfect! 4 people tomorrow at 19:00. May I have your phone number?',
    has_markdown: false,
    has_greeting: false,
    tts_situation: 'normal',
    tts_mood: 'helpful',
    tts_suppressed_reason: null,
    validation_breakdown: {
      date: 'verified',
      party_size: 'verified',
    },
    build_sha: 'abc1234',
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    call_id: 'test-call-1',
    call_sid: 'test-call-1-sid',
    tenant_id: 'doboo',
    turn_number: 3,
    user_text: '+49 30 1234567',
    bot_text: 'Danke! Deine Reservation ist bestätigt. Dein Buchungscode ist ABC123.',
    vad_start_ms: 5200,
    vad_stop_ms: 6500,
    stt_confidence: 0.88,
    stt_latency_ms: 220,
    llm_latency_ms: 480,
    tts_latency_ms: 900,
    tts_ttfb_ms: 250,
    total_latency_ms: 1800,
    acoustic_gap_ms: 60,
    tools_called: ['verify_address', 'create_reservation'],
    node_name: 'READBACK',
    layer1_decision: {
      node: 'READBACK',
      forced_tools: [],
      state_hash: 'hash_3',
      validators_run: [
        {
          slot: 'phone',
          status: 'verified',
          duration_ms: 100,
          retry: 0,
        },
      ],
    },
    layer2_raw_output: 'phone_validated',
    layer3_changes: {
      warnings: [],
      text_changed: false,
      tools_changed: false,
    },
    stage1_clean_text: '+49 30 1234567',
    stage2_clean_text: '+49 30 1234567',
    stage3_text: 'Thanks! Your reservation is confirmed. Your booking code is ABC123.',
    has_markdown: false,
    has_greeting: false,
    tts_situation: 'normal',
    tts_mood: 'positive',
    tts_suppressed_reason: null,
    validation_breakdown: {
      phone: 'verified',
    },
    build_sha: 'abc1234',
    created_at: new Date().toISOString(),
  },
];

// Mock fixture: call with warning
const fixtureWithWarning: TurnRow[] = [
  {
    id: 1,
    call_id: 'test-call-2',
    call_sid: 'test-call-2-sid',
    tenant_id: 'doboo',
    turn_number: 1,
    user_text: 'Ich möchte Pizza bestellen',
    bot_text: 'Gerne! Welche Pizza magst du?',
    vad_start_ms: 100,
    vad_stop_ms: 1500,
    stt_confidence: 0.85,
    stt_latency_ms: 250,
    llm_latency_ms: 400,
    tts_latency_ms: 1100,
    tts_ttfb_ms: 320,
    total_latency_ms: 1800,
    acoustic_gap_ms: 80,
    tools_called: [],
    node_name: 'GREETING',
    layer1_decision: {
      node: 'GREETING',
      forced_tools: [],
      state_hash: 'warn_hash_1',
      validators_run: [],
    },
    layer2_raw_output: 'greeting',
    layer3_changes: {
      warnings: [],
      text_changed: false,
      tools_changed: false,
    },
    stage1_clean_text: 'I want to order pizza',
    stage2_clean_text: 'I want to order pizza',
    stage3_text: 'Sure! What pizza would you like?',
    has_markdown: false,
    has_greeting: true,
    tts_situation: 'normal',
    tts_mood: 'friendly',
    tts_suppressed_reason: null,
    validation_breakdown: {},
    build_sha: 'def5678',
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    call_id: 'test-call-2',
    call_sid: 'test-call-2-sid',
    tenant_id: 'doboo',
    turn_number: 2,
    user_text: 'Die Margherita bitte',
    bot_text: 'Mmmm, gute Wahl! Die Margherita ist unsere beliebteste Pizza.',
    vad_start_ms: 1600,
    vad_stop_ms: 3200,
    stt_confidence: 0.79,
    stt_latency_ms: 290,
    llm_latency_ms: 520,
    tts_latency_ms: 1300,
    tts_ttfb_ms: 350,
    total_latency_ms: 2100,
    acoustic_gap_ms: 90,
    tools_called: ['get_menu'],
    node_name: 'ORDER_OR_RESERVE',
    layer1_decision: {
      node: 'ORDER_OR_RESERVE',
      forced_tools: ['get_menu'],
      state_hash: 'warn_hash_2',
      validators_run: [
        {
          slot: 'menu_item',
          status: 'verified',
          duration_ms: 40,
          retry: 0,
        },
      ],
    },
    layer2_raw_output: 'menu_item_extract',
    layer3_changes: {
      warnings: [
        {
          kind: 'confidence_low',
          message: 'STT confidence 0.79 below threshold 0.80',
        },
      ],
      text_changed: false,
      tools_changed: false,
    },
    stage1_clean_text: 'The Margherita please',
    stage2_clean_text: 'The Margherita please',
    stage3_text: 'Mmm, good choice! The Margherita is our most popular pizza.',
    has_markdown: false,
    has_greeting: false,
    tts_situation: 'normal',
    tts_mood: 'encouraging',
    tts_suppressed_reason: null,
    validation_breakdown: {
      menu_item: 'verified',
    },
    build_sha: 'def5678',
    created_at: new Date().toISOString(),
  },
];

export const MOCK_SESSIONS: SessionRow[] = [
  {
    call_sid: 'test-call-1-sid',
    tenant_id: 'doboo',
    started_at: new Date(Date.now() - 3600000).toISOString(),
    duration_seconds: 180,
    turn_count: 3,
    ended_properly: true,
    build_sha: 'abc1234',
  },
  {
    call_sid: 'test-call-2-sid',
    tenant_id: 'doboo',
    started_at: new Date(Date.now() - 1800000).toISOString(),
    duration_seconds: 120,
    turn_count: 2,
    ended_properly: false,
    build_sha: 'def5678',
  },
];

export const MOCK_CALL_TURNS = {
  'test-call-1-sid': {
    call_sid: 'test-call-1-sid',
    turn_count: 3,
    turns: fixtureHappyPath,
  },
  'test-call-2-sid': {
    call_sid: 'test-call-2-sid',
    turn_count: 2,
    turns: fixtureWithWarning,
  },
};
