"""
Phase 2 — Tool-Call Inquiries — Scenarios

Rebuilt by server/training/rebuild_scenarios.py (deduplicated + enriched with caller data).
"""

from server.scenarios.base import AudioScenario, ScenarioTurn

PHASE2_SCENARIOS = [
AudioScenario(
    id="p2-reservation-001",
    phase="phase2",
    category="reservation",
    description="Reservierung für 4 Personen am Samstagabend",
    persona="neutral",
    noise_variant="clean",
    goal="Reserve a table for 4 people this Saturday at 7 PM. Provide your name and phone when asked.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-002",
    phase="phase2",
    category="order",
    description="Lieferbestellung von Bibimbap unter 15€",
    persona="impatient",
    noise_variant="speakerphone",
    goal="Order Bulgogi for home delivery. Give your delivery address and contact details only when the agent asks.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    caller_address="Friedrichstr. 18, 10117 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "verify_address", "send_sms"],
),
AudioScenario(
    id="p2-faq-003",
    phase="phase2",
    category="faq",
    description="Frage nach Parkmöglichkeiten",
    persona="accent",
    noise_variant="clean",
    turns=[
        ScenarioTurn(user_utterance="Hallo, I have a question."),
        ScenarioTurn(user_utterance="Where can I park near your restaurant?"),
        ScenarioTurn(user_utterance="Is it close to the entrance?"),
        ScenarioTurn(user_utterance="Ah, just 200 meters. Dankeschön."),
        ScenarioTurn(user_utterance="Yes, perfect."),
        ScenarioTurn(user_utterance="Thanks a lot! Bye!"),
        ScenarioTurn(user_utterance="Auf Wiedersehen!"),
    ],
    expected_tools=[],
),
AudioScenario(
    id="p2-reservation-004",
    phase="phase2",
    category="reservation",
    description="Reservierung für 2 Personen am Freitagmittag",
    persona="sleepy",
    noise_variant="restaurant_bg",
    goal="Reserve a table for 6 people on Sunday at 1 PM. Provide name and phone number when asked.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-005",
    phase="phase2",
    category="order",
    description="Abholbestellung von Bulgogi",
    persona="hard_to_hear",
    noise_variant="street",
    goal="Order Japchae for delivery. Be polite but brief.",
    caller_name="Stefan Bauer",
    caller_phone="+49 151 22223333",
    caller_address="Schönhauser Allee 55, 10437 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order"],
),
AudioScenario(
    id="p2-order-001",
    phase="phase2",
    category="order",
    description="Bestellung von Bibimbap zur Lieferung",
    persona="neutral",
    noise_variant="clean",
    goal="Order Mandu for delivery to your home address. When asked, provide your name, address, and phone number.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    caller_address="Prenzlauer Allee 12, 10405 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "verify_address", "send_sms"],
),
AudioScenario(
    id="p2-reservation-002",
    phase="phase2",
    category="reservation",
    description="Reservierung für vier Personen",
    persona="impatient",
    noise_variant="clean",
    goal="Book a table for 2 people tonight at 8 PM. Give your contact details when the agent asks.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-004",
    phase="phase2",
    category="order",
    description="Bulgogi-Bestellung zur Abholung",
    persona="accent",
    noise_variant="clean",
    goal="Order Tofu Bibimbap to take away. Confirm your order clearly when asked.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    caller_address="Friedrichstr. 18, 10117 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "send_sms"],
),
AudioScenario(
    id="p2-reservation-005",
    phase="phase2",
    category="reservation",
    description="Reservierung für zwei Personen am Sonntag",
    persona="hard_to_hear",
    noise_variant="street",
    goal="Reserve a table for 6 people on Sunday at 1 PM. Provide name and phone number when asked.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-faq-006",
    phase="phase2",
    category="faq",
    description="Frage zu den Öffnungszeiten an Feiertagen",
    persona="neutral",
    noise_variant="clean",
    turns=[
        ScenarioTurn(user_utterance="Hallo, ich habe eine Frage."),
        ScenarioTurn(user_utterance="Wie sind Ihre Öffnungszeiten an Feiertagen?"),
        ScenarioTurn(user_utterance="Hm, verstehe. Danke für die Info."),
        ScenarioTurn(user_utterance="Nein, das wäre alles."),
        ScenarioTurn(user_utterance="Alles klar, danke."),
        ScenarioTurn(user_utterance="Ja, auf Wiederhören."),
    ],
    expected_tools=["get_date_info"],
),
AudioScenario(
    id="p2-order-007",
    phase="phase2",
    category="order",
    description="Kimchi-Bestellung zur Lieferung",
    persona="sleepy",
    noise_variant="restaurant_bg",
    goal="Order Kimchi Jjigae for delivery to your home address. When asked, provide your name, address, and phone number.",
    caller_name="Stefan Bauer",
    caller_phone="+49 151 22223333",
    caller_address="Schönhauser Allee 55, 10437 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "verify_address", "send_sms"],
),
AudioScenario(
    id="p2-reservation-008",
    phase="phase2",
    category="reservation",
    description="Tischreservierung für fünf Personen",
    persona="accent",
    noise_variant="clean",
    goal="Book a table for 2 people tonight at 8 PM. Give your contact details when the agent asks.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-faq-009",
    phase="phase2",
    category="faq",
    description="Frage zu Zahlung mit PayPal",
    persona="impatient",
    noise_variant="street",
    turns=[
        ScenarioTurn(user_utterance="Hallo, kann ich mit PayPal zahlen?"),
        ScenarioTurn(user_utterance="Nicht? Oh Mann, okay."),
        ScenarioTurn(user_utterance="Ja, alles andere geht?"),
        ScenarioTurn(user_utterance="Ja, danke."),
        ScenarioTurn(user_utterance="Tschüss dann."),
    ],
    expected_tools=[],
),
AudioScenario(
    id="p2-order-010",
    phase="phase2",
    category="order",
    description="Tteokbokki zur Lieferung",
    persona="hard_to_hear",
    noise_variant="restaurant_bg",
    goal="Order Mandu for delivery. You are in a hurry but provide all required details when asked.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    caller_address="Friedrichstr. 18, 10117 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "verify_address", "send_sms"],
),
AudioScenario(
    id="p2-reservation-036",
    phase="phase2",
    category="reservation",
    description="Reservierung für 4 am Samstagabend",
    persona="neutral",
    noise_variant="clean",
    goal="Book a table for 2 for tomorrow evening at 7:30 PM. Answer all questions clearly.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-037",
    phase="phase2",
    category="order",
    description="Bibimbap und Bulgogi zur Lieferung",
    persona="accent",
    noise_variant="speakerphone",
    goal="Order Tofu Bibimbap for delivery to your home address. When asked, provide your name, address, and phone number.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    caller_address="Karl-Marx-Allee 101, 10243 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "send_sms", "verify_address"],
),
AudioScenario(
    id="p2-faq-038",
    phase="phase2",
    category="faq",
    description="Frage nach Parkmöglichkeiten",
    persona="hard_to_hear",
    noise_variant="street",
    turns=[
        ScenarioTurn(user_utterance="Hallo, ich hätte eine kurze Frage."),
        ScenarioTurn(user_utterance="Gibt es Parkmöglichkeiten bei Ihnen?"),
        ScenarioTurn(user_utterance="Wie weit ist das Parkhaus entfernt?"),
        ScenarioTurn(user_utterance="Okay, 200 Meter, alles klar."),
        ScenarioTurn(user_utterance="Danke, das ist hilfreich."),
        ScenarioTurn(user_utterance="Ja, danke schön."),
        ScenarioTurn(user_utterance="Auf Wiederhören."),
    ],
    expected_tools=[],
),
AudioScenario(
    id="p2-reservation-039",
    phase="phase2",
    category="reservation",
    description="Reservierung für 2 Personen am Donnerstag",
    persona="sleepy",
    noise_variant="clean",
    goal="Make a reservation for 3 people on Friday at 6:30 PM. Confirm when asked.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-040",
    phase="phase2",
    category="order",
    description="Kimbap und Tteokbokki zur Abholung",
    persona="impatient",
    noise_variant="restaurant_bg",
    goal="Order Kimchi Jjigae for delivery. You are in a hurry but provide all required details when asked.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    caller_address="Berliner Str. 42, 10115 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "send_sms"],
),
AudioScenario(
    id="p2-order-041",
    phase="phase2",
    category="order",
    description="Kimchi und Ramyeon zur Lieferung",
    persona="neutral",
    noise_variant="clean",
    goal="Order Tteokbokki for delivery. Be polite but brief.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    caller_address="Friedrichstr. 18, 10117 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "send_sms", "verify_address"],
),
AudioScenario(
    id="p2-reservation-042",
    phase="phase2",
    category="reservation",
    description="Reservierung für 6 am Freitag",
    persona="accent",
    noise_variant="street",
    goal="Reserve a table for 4 people this Saturday at 7 PM. Provide your name and phone when asked.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-043",
    phase="phase2",
    category="order",
    description="Bulgogi zur Abholung",
    persona="impatient",
    noise_variant="restaurant_bg",
    goal="Order Mandu for home delivery. Give your delivery address and contact details only when the agent asks.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    caller_address="Karl-Marx-Allee 101, 10243 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "send_sms"],
),
AudioScenario(
    id="p2-faq-044",
    phase="phase2",
    category="faq",
    description="Frage nach veganen Optionen",
    persona="neutral",
    noise_variant="clean",
    turns=[
        ScenarioTurn(user_utterance="Hallo, ich habe eine Frage zu Ihrem Menü."),
        ScenarioTurn(user_utterance="Haben Sie vegane Optionen?"),
        ScenarioTurn(user_utterance="Könnten Sie mir einige Beispiele nennen?"),
        ScenarioTurn(user_utterance="Okay, klingt gut, danke."),
        ScenarioTurn(user_utterance="Ja, danke für die Info."),
        ScenarioTurn(user_utterance="Auf Wiederhören, danke."),
    ],
    expected_tools=[],
),
AudioScenario(
    id="p2-reservation-045",
    phase="phase2",
    category="reservation",
    description="Reservierung für 3 Personen am Dienstag",
    persona="hard_to_hear",
    noise_variant="speakerphone",
    goal="Reserve a table for 6 people on Sunday at 1 PM. Provide name and phone number when asked.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-046",
    phase="phase2",
    category="order",
    description="Ramyeon zur Abholung",
    persona="sleepy",
    noise_variant="clean",
    goal="Order Bibimbap for delivery. Be polite but brief.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    caller_address="Berliner Str. 42, 10115 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "send_sms"],
),
AudioScenario(
    id="p2-reservation-047",
    phase="phase2",
    category="reservation",
    description="Reservierung für 5 Personen für heute Abend",
    persona="accent",
    noise_variant="restaurant_bg",
    goal="Reserve a table for 4 people this Saturday at 7 PM. Provide your name and phone when asked.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-faq-048",
    phase="phase2",
    category="faq",
    description="Frage nach Menü-Highlights",
    persona="neutral",
    noise_variant="clean",
    turns=[
        ScenarioTurn(user_utterance="Hallo, ich interessiere mich für Ihre Menü-Highlights."),
        ScenarioTurn(user_utterance="Könnten Sie mir einige Empfehlungen geben?"),
        ScenarioTurn(user_utterance="Oh, das klingt alles lecker."),
        ScenarioTurn(user_utterance="Haben Sie das jeden Tag verfügbar?"),
        ScenarioTurn(user_utterance="Super, danke."),
        ScenarioTurn(user_utterance="Ja, sehr hilfreich. Danke nochmals."),
        ScenarioTurn(user_utterance="Auf Wiederhören."),
    ],
    expected_tools=[],
),
AudioScenario(
    id="p2-order-049",
    phase="phase2",
    category="order",
    description="Bibimbap zur Lieferung",
    persona="hard_to_hear",
    noise_variant="street",
    goal="Order Tteokbokki to take away. Confirm your order clearly when asked.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    caller_address="Karl-Marx-Allee 101, 10243 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "send_sms", "verify_address"],
),
AudioScenario(
    id="p2-reservation-050",
    phase="phase2",
    category="reservation",
    description="Reservierung für 8 am nächsten Samstag",
    persona="impatient",
    noise_variant="clean",
    goal="Reserve a table for 6 people on Sunday at 1 PM. Provide name and phone number when asked.",
    caller_name="Stefan Bauer",
    caller_phone="+49 151 22223333",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-reservation-37",
    phase="phase2",
    category="reservation",
    description="Reservierung für Samstagabend",
    persona="neutral",
    noise_variant="clean",
    goal="Book a table for 2 for tomorrow evening at 7:30 PM. Answer all questions clearly.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-38",
    phase="phase2",
    category="order",
    description="Lieferbestellung nach Hause",
    persona="impatient",
    noise_variant="street",
    goal="Order Tofu Jjigae for delivery to your home address. When asked, provide your name, address, and phone number.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    caller_address="Berliner Str. 42, 10115 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "verify_address", "send_sms"],
),
AudioScenario(
    id="p2-faq-39",
    phase="phase2",
    category="faq",
    description="Fragen zu Lieferoptionen",
    persona="accent",
    noise_variant="restaurant_bg",
    turns=[
        ScenarioTurn(user_utterance="Hello, I have a question about delivery."),
        ScenarioTurn(user_utterance="Do you deliver to Poppelsdorf?"),
        ScenarioTurn(user_utterance="Oh, okay. And there is a minimum order value, right?"),
        ScenarioTurn(user_utterance="Got it. Danke schön."),
        ScenarioTurn(user_utterance="No, that was all. Bye."),
    ],
    expected_tools=["get_menu"],
),
AudioScenario(
    id="p2-reservation-40",
    phase="phase2",
    category="reservation",
    description="Reservierung für Mittagessen",
    persona="sleepy",
    noise_variant="clean",
    goal="Make a reservation for 3 people on Friday at 6:30 PM. Confirm when asked.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-41",
    phase="phase2",
    category="order",
    description="Bestellung für Abholung",
    persona="hard_to_hear",
    noise_variant="restaurant_bg",
    goal="Order Bulgogi for delivery. You are in a hurry but provide all required details when asked.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    caller_address="Karl-Marx-Allee 101, 10243 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order"],
),
AudioScenario(
    id="p2-faq-42",
    phase="phase2",
    category="faq",
    description="Fragen zu Speisekarte und Öffnungszeiten",
    persona="neutral",
    noise_variant="clean",
    turns=[
        ScenarioTurn(user_utterance="Hallo, ich habe ein paar Fragen zur Speisekarte."),
        ScenarioTurn(user_utterance="Haben Sie auch vegetarische Gerichte?"),
        ScenarioTurn(user_utterance="Und wann haben Sie geöffnet?"),
        ScenarioTurn(user_utterance="Alles klar, danke für die Infos."),
        ScenarioTurn(user_utterance="Nein, das war's. Auf Wiederhören."),
    ],
    expected_tools=["get_menu", "get_date_info"],
),
AudioScenario(
    id="p2-reservation-43",
    phase="phase2",
    category="reservation",
    description="Reservierungsanfrage für eine größere Gruppe",
    persona="impatient",
    noise_variant="speakerphone",
    goal="Reserve a table for 4 people this Saturday at 7 PM. Provide your name and phone when asked.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-44",
    phase="phase2",
    category="order",
    description="Telefonische Bestellung von Spezialitäten",
    persona="accent",
    noise_variant="street",
    goal="Order Japchae for home delivery. Give your delivery address and contact details only when the agent asks.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    caller_address="Berliner Str. 42, 10115 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "verify_address", "send_sms"],
),
AudioScenario(
    id="p2-faq-45",
    phase="phase2",
    category="faq",
    description="Fragen zum Bezahlmöglichkeiten",
    persona="sleepy",
    noise_variant="restaurant_bg",
    turns=[
        ScenarioTurn(user_utterance="Hallo... Ich wollte fragen wegen... Bezahlung."),
        ScenarioTurn(user_utterance="Welche Zahlungsmöglichkeiten... haben Sie?"),
        ScenarioTurn(user_utterance="Okay... danke."),
        ScenarioTurn(user_utterance="Nein... das reicht... Tschüss."),
    ],
    expected_tools=[],
),
AudioScenario(
    id="p2-reservation-46",
    phase="phase2",
    category="reservation",
    description="Kurzfristige Reservierung für den Abend",
    persona="hard_to_hear",
    noise_variant="street",
    goal="Reserve a table for 6 people on Sunday at 1 PM. Provide name and phone number when asked.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-47",
    phase="phase2",
    category="order",
    description="Telefonische Bestellung mit mehreren Gerichten",
    persona="neutral",
    noise_variant="clean",
    goal="Order Tofu Bibimbap for delivery. Be polite but brief.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    caller_address="Karl-Marx-Allee 101, 10243 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "verify_address", "send_sms"],
),
AudioScenario(
    id="p2-faq-48",
    phase="phase2",
    category="faq",
    description="Erkundigt sich nach Parkmöglichkeiten",
    persona="accent",
    noise_variant="street",
    turns=[
        ScenarioTurn(user_utterance="Hallo, do you have parking?"),
        ScenarioTurn(user_utterance="Okay, and it's easy to reach?"),
        ScenarioTurn(user_utterance="Thank you very much."),
        ScenarioTurn(user_utterance="No, that's all. Bye."),
    ],
    expected_tools=[],
),
AudioScenario(
    id="p2-reservation-49",
    phase="phase2",
    category="reservation",
    description="Reservierung für Überraschungsdinner",
    persona="neutral",
    noise_variant="restaurant_bg",
    goal="Book a table for 2 people tonight at 8 PM. Give your contact details when the agent asks.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-50",
    phase="phase2",
    category="order",
    description="Bestellung und Nachfrage zu Besonderheiten",
    persona="sleepy",
    noise_variant="clean",
    goal="Order Kimchi Jjigae to take away. Confirm your order clearly when asked.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    caller_address="Berliner Str. 42, 10115 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "verify_address", "send_sms"],
),
AudioScenario(
    id="p2-order-delivery-21",
    phase="phase2",
    category="order-delivery",
    description="Anrufer bestellt Ramyeon zur Lieferung",
    persona="neutral",
    noise_variant="clean",
    goal="Order Tteokbokki for delivery. You are in a hurry but provide all required details when asked.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "verify_address", "send_sms"],
),
AudioScenario(
    id="p2-reservaion-22",
    phase="phase2",
    category="reservation",
    description="Anrufer reserviert Tisch für 4 Personen",
    persona="impatient",
    noise_variant="street",
    goal="Book a table for 2 for tomorrow evening at 7:30 PM. Answer all questions clearly.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-faq-menu-23",
    phase="phase2",
    category="faq",
    description="Anrufer fragt nach Speisekarte",
    persona="sleepy",
    noise_variant="clean",
    turns=[
        ScenarioTurn(user_utterance="Hallo, ja, guten Tag..."),
        ScenarioTurn(user_utterance="Ich wollte fragen... was gibt's zu essen..."),
        ScenarioTurn(user_utterance="Ja... bitte..."),
        ScenarioTurn(user_utterance="Ah... klingt gut... danke..."),
        ScenarioTurn(user_utterance="Ja, danke... Tschüss."),
    ],
    expected_tools=["get_menu"],
),
AudioScenario(
    id="p2-faq-delivery-area-24",
    phase="phase2",
    category="faq",
    description="Anrufer fragt nach Liefergebiet",
    persona="accent",
    noise_variant="restaurant_bg",
    turns=[
        ScenarioTurn(user_utterance="Guten Tag, do you deliver to Poppelsdorf?"),
        ScenarioTurn(user_utterance="Ah, okay, I understand. Only city center, ja?"),
        ScenarioTurn(user_utterance="Danke for the info."),
        ScenarioTurn(user_utterance="Danke, tschüss."),
    ],
    expected_tools=[],
),
AudioScenario(
    id="p2-order-pickup-25",
    phase="phase2",
    category="order-pickup",
    description="Anrufer bestellt Tteokbokki zur Abholung",
    persona="hard_to_hear",
    noise_variant="street",
    goal="Anrufer bestellt Tteokbokki zur Abholung. Provide your name, address and phone only when the agent explicitly asks.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order"],
),
AudioScenario(
    id="p2-order-26",
    phase="phase2",
    category="order",
    description="Anruf für eine Bibimbap-Bestellung zur Abholung",
    persona="neutral",
    noise_variant="clean",
    goal="Order Bibimbap for delivery. You are in a hurry but provide all required details when asked.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    caller_address="Berliner Str. 42, 10115 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order"],
),
AudioScenario(
    id="p2-reservation-16",
    phase="phase2",
    category="reservation",
    description="Reservierung für 3 Personen am Freitagabend",
    persona="impatient",
    noise_variant="clean",
    goal="Book a table for 2 for tomorrow evening at 7:30 PM. Answer all questions clearly.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-27",
    phase="phase2",
    category="order",
    description="Lieferung einer Bestellung nach Bonn Innenstadt",
    persona="accent",
    noise_variant="street",
    goal="Order Kimchi Jjigae for delivery to your home address. When asked, provide your name, address, and phone number.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    caller_address="Kastanienallee 7, 10435 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "verify_address"],
),
AudioScenario(
    id="p2-reservation-17",
    phase="phase2",
    category="reservation",
    description="Tischreservierung für 6 Personen am Samstag",
    persona="sleepy",
    noise_variant="restaurant_bg",
    goal="Book a table for 2 people tonight at 8 PM. Give your contact details when the agent asks.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-28",
    phase="phase2",
    category="order",
    description="Abholung von zwei Ramyeon",
    persona="hard_to_hear",
    noise_variant="street",
    goal="Order Japchae to take away. Confirm your order clearly when asked.",
    caller_name="Stefan Bauer",
    caller_phone="+49 151 22223333",
    caller_address="Schönhauser Allee 55, 10437 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order"],
),
AudioScenario(
    id="p2-reservation-18",
    phase="phase2",
    category="reservation",
    description="Reservierung für 2 auf Namen Meyer",
    persona="neutral",
    noise_variant="clean",
    goal="Reserve a table for 6 people on Sunday at 1 PM. Provide name and phone number when asked.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-29",
    phase="phase2",
    category="order",
    description="Bestellung für Bulgogi mit Lieferung",
    persona="impatient",
    noise_variant="restaurant_bg",
    goal="Order Tofu Jjigae for delivery. Be polite but brief.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    caller_address="Berliner Str. 42, 10115 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "verify_address"],
),
AudioScenario(
    id="p2-reservation-19",
    phase="phase2",
    category="reservation",
    description="Reservierung für 4 Personen, schnell bestätigt",
    persona="impatient",
    noise_variant="clean",
    goal="Reserve a table for 4 people this Saturday at 7 PM. Provide your name and phone when asked.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-faq-06",
    phase="phase2",
    category="faq",
    description="Anfrage zur Parkplatzinformation",
    persona="neutral",
    noise_variant="clean",
    turns=[
        ScenarioTurn(user_utterance="Guten Tag, ich hätte eine Frage."),
        ScenarioTurn(user_utterance="Wo kann ich parken, wenn ich zu Ihnen komme?"),
        ScenarioTurn(user_utterance="Ah, das Rheinufer-Parkhaus, okay."),
        ScenarioTurn(user_utterance="Und das ist etwa 200 Meter entfernt, richtig?"),
        ScenarioTurn(user_utterance="Danke für die Info!"),
        ScenarioTurn(user_utterance="Alles klar, dann bis bald."),
        ScenarioTurn(user_utterance="Tschüss!"),
    ],
    expected_tools=[],
),
AudioScenario(
    id="p2-order-30",
    phase="phase2",
    category="order",
    description="Lieferung von Kimchi und Ramyeon",
    persona="accent",
    noise_variant="speakerphone",
    goal="Order Bulgogi to take away. Confirm your order clearly when asked.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    caller_address="Karl-Marx-Allee 101, 10243 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "verify_address"],
),
AudioScenario(
    id="p2-order-37",
    phase="phase2",
    category="order",
    description="Anrufer will Bulgogi bestellen",
    persona="neutral",
    noise_variant="clean",
    goal="Order Kimchi Jjigae for delivery. You are in a hurry but provide all required details when asked.",
    caller_name="Stefan Bauer",
    caller_phone="+49 151 22223333",
    caller_address="Schönhauser Allee 55, 10437 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "verify_address", "send_sms"],
),
AudioScenario(
    id="p2-reservation-38",
    phase="phase2",
    category="reservation",
    description="Reservierung für 4 Personen am Samstag",
    persona="accent",
    noise_variant="restaurant_bg",
    goal="Book a table for 2 for tomorrow evening at 7:30 PM. Answer all questions clearly.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation", "send_sms"],
),
AudioScenario(
    id="p2-order-40",
    phase="phase2",
    category="order",
    description="Kimbap und Tteokbokki zur Abholung",
    persona="sleepy",
    noise_variant="clean",
    goal="Order Japchae for delivery to your home address. When asked, provide your name, address, and phone number.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    caller_address="Berliner Str. 42, 10115 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "send_sms"],
),
AudioScenario(
    id="p2-order-31",
    phase="phase2",
    category="order",
    description="Ungeduldig fragt nach Kimchi Bestellung",
    persona="impatient",
    noise_variant="clean",
    goal="Order Mandu for home delivery. Give your delivery address and contact details only when the agent asks.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    caller_address="Friedrichstr. 18, 10117 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "send_sms", "verify_address"],
),
AudioScenario(
    id="p2-reservation-32",
    phase="phase2",
    category="reservation",
    description="Schläfrig fragt nach Reservierung für 2",
    persona="sleepy",
    noise_variant="street",
    goal="Make a reservation for 3 people on Friday at 6:30 PM. Confirm when asked.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-33",
    phase="phase2",
    category="order",
    description="Koreanisch Akzent, bestellt Ramyeon",
    persona="accent",
    noise_variant="restaurant_bg",
    goal="Order Tofu Bibimbap for delivery. You are in a hurry but provide all required details when asked.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    caller_address="Karl-Marx-Allee 101, 10243 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "send_sms", "verify_address"],
),
AudioScenario(
    id="p2-faq-34",
    phase="phase2",
    category="faq",
    description="Leise Anrufer fragt nach Öffnungszeiten",
    persona="hard_to_hear",
    noise_variant="street",
    turns=[
        ScenarioTurn(user_utterance="Hallo, wann habt ihr offen?"),
        ScenarioTurn(user_utterance="Ja, in der Woche."),
        ScenarioTurn(user_utterance="Und samstags?"),
        ScenarioTurn(user_utterance="Okay, danke, ja."),
        ScenarioTurn(user_utterance="Nein, mehr nicht."),
        ScenarioTurn(user_utterance="Ja, alles klar."),
        ScenarioTurn(user_utterance="Tschüss, danke."),
    ],
    expected_tools=["get_date_info"],
),
AudioScenario(
    id="p2-reservation-28",
    phase="phase2",
    category="reservation",
    description="Reservierung für 5 Personen am Wochenende",
    persona="neutral",
    noise_variant="clean",
    goal="Reserve a table for 4 people this Saturday at 7 PM. Provide your name and phone when asked.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-faq-29",
    phase="phase2",
    category="faq",
    description="Frage zu Parkmöglichkeiten mit lautem Hintergrund",
    persona="hard_to_hear",
    noise_variant="street",
    turns=[
        ScenarioTurn(user_utterance="Hallo, können Sie mich hören?"),
        ScenarioTurn(user_utterance="Wo kann man parken?"),
        ScenarioTurn(user_utterance="Ist es weit entfernt?"),
        ScenarioTurn(user_utterance="Rheinufer-Parkhaus, richtig?"),
        ScenarioTurn(user_utterance="Ah, 200 Meter... okay..."),
        ScenarioTurn(user_utterance="Ja, das passt so."),
        ScenarioTurn(user_utterance="Danke für die Info, tschüss."),
    ],
    expected_tools=[],
),
AudioScenario(
    id="p2-reservation-01",
    phase="phase2",
    category="reservation",
    description="Reservierung für Abendessen am Samstag",
    persona="neutral",
    noise_variant="clean",
    goal="Make a reservation for 3 people on Friday at 6:30 PM. Confirm when asked.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-02",
    phase="phase2",
    category="order",
    description="Bestellung von Bibimbap zur Lieferung",
    persona="impatient",
    noise_variant="street",
    goal="Order Japchae for delivery. You are in a hurry but provide all required details when asked.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    caller_address="Kastanienallee 7, 10435 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "verify_address", "send_sms"],
),
AudioScenario(
    id="p2-delivery-03",
    phase="phase2",
    category="order",
    description="Lieferanfrage für Kimchi und Kimbap",
    persona="accent",
    noise_variant="speakerphone",
    goal="Order Mandu for delivery. Be polite but brief.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    caller_address="Karl-Marx-Allee 101, 10243 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "verify_address", "send_sms"],
),
AudioScenario(
    id="p2-faq-04",
    phase="phase2",
    category="faq",
    description="Frage zu Zahlung mit Kreditkarte",
    persona="neutral",
    noise_variant="clean",
    turns=[
        ScenarioTurn(user_utterance="Hallo, kann ich bei Ihnen mit Kreditkarte zahlen?"),
        ScenarioTurn(user_utterance="Interessant, danke für die Information."),
        ScenarioTurn(user_utterance="Okay, das passt gut. Vielen Dank."),
        ScenarioTurn(user_utterance="Ja, das war's. Tschüss."),
    ],
    expected_tools=[],
),
AudioScenario(
    id="p2-order-05",
    phase="phase2",
    category="order",
    description="Bestellung von Tteokbokki zur Abholung",
    persona="sleepy",
    noise_variant="restaurant_bg",
    goal="Order Tofu Bibimbap for home delivery. Give your delivery address and contact details only when the agent asks.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    caller_address="Prenzlauer Allee 12, 10405 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "send_sms"],
),
AudioScenario(
    id="p2-reservation-06",
    phase="phase2",
    category="reservation",
    description="Tisch für zwei Personen am Freitag reservieren",
    persona="hard_to_hear",
    noise_variant="street",
    goal="Make a reservation for 3 people on Friday at 6:30 PM. Confirm when asked.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-07",
    phase="phase2",
    category="order",
    description="Bulgogi und Ramyeon bestellen, Abholung",
    persona="neutral",
    noise_variant="clean",
    goal="Order Bulgogi for delivery. You are in a hurry but provide all required details when asked.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    caller_address="Friedrichstr. 18, 10117 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "send_sms"],
),
AudioScenario(
    id="p2-faq-08",
    phase="phase2",
    category="faq",
    description="Frage zu den Öffnungszeiten",
    persona="accent",
    noise_variant="restaurant_bg",
    turns=[
        ScenarioTurn(user_utterance="Hello, what are your opening... äh... Öffnungszeiten?"),
        ScenarioTurn(user_utterance="Ah, okay, danke!"),
        ScenarioTurn(user_utterance="Yes, that helps, vielen Dank."),
        ScenarioTurn(user_utterance="Okay, bye."),
    ],
    expected_tools=["get_date_info"],
),
AudioScenario(
    id="p2-reservation-09",
    phase="phase2",
    category="reservation",
    description="Gehobene Reservierung mit Familie",
    persona="impatient",
    noise_variant="speakerphone",
    goal="Reserve a table for 4 people this Saturday at 7 PM. Provide your name and phone when asked.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-10",
    phase="phase2",
    category="order",
    description="Kimchi und Bulgogi zur Lieferung",
    persona="hard_to_hear",
    noise_variant="street",
    goal="Order Japchae for home delivery. Give your delivery address and contact details only when the agent asks.",
    caller_name="Stefan Bauer",
    caller_phone="+49 151 22223333",
    caller_address="Schönhauser Allee 55, 10437 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "verify_address", "send_sms"],
),
AudioScenario(
    id="p2-order-01",
    phase="phase2",
    category="order",
    description="Bestellung von Bibimbap zur Lieferung",
    persona="neutral",
    noise_variant="clean",
    goal="Order Mandu to take away. Confirm your order clearly when asked.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    caller_address="Prenzlauer Allee 12, 10405 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "send_sms"],
),
AudioScenario(
    id="p2-faq-01",
    phase="phase2",
    category="faq",
    description="Frage nach Parkplatzmöglichkeiten",
    persona="hard_to_hear",
    noise_variant="street",
    turns=[
        ScenarioTurn(user_utterance="Hallo... Parkplatz?"),
        ScenarioTurn(user_utterance="Ja, parken, wo?"),
        ScenarioTurn(user_utterance="Ah... okay, danke... nähere Infos?"),
        ScenarioTurn(user_utterance="Super, danke... das war's."),
        ScenarioTurn(user_utterance="Nein, tschüss..."),
        ScenarioTurn(user_utterance="Danke."),
    ],
    expected_tools=[],
),
AudioScenario(
    id="p2-order-03",
    phase="phase2",
    category="order",
    description="Bestellung von Bulgogi zur Abholung",
    persona="sleepy",
    noise_variant="restaurant_bg",
    goal="Order Tofu Bibimbap for delivery. Be polite but brief.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    caller_address="Friedrichstr. 18, 10117 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "send_sms"],
),
AudioScenario(
    id="p2-reservation-02",
    phase="phase2",
    category="reservation",
    description="Reservierung für Donnerstag 18 Uhr, 2 Personen",
    persona="neutral",
    noise_variant="clean",
    goal="Reserve a table for 4 people this Saturday at 7 PM. Provide your name and phone when asked.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-faq-02",
    phase="phase2",
    category="faq",
    description="Frage zu den Zahlungsmöglichkeiten",
    persona="impatient",
    noise_variant="speakerphone",
    turns=[
        ScenarioTurn(user_utterance="Hallo, welche Zahlungsmethoden?"),
        ScenarioTurn(user_utterance="Kein PayPal?"),
        ScenarioTurn(user_utterance="Okay, danke."),
        ScenarioTurn(user_utterance="Nein, tschüss!"),
    ],
    expected_tools=[],
),
AudioScenario(
    id="p2-order-04",
    phase="phase2",
    category="order",
    description="Bestellung von Kimchi und Kimbap zur Abholung",
    persona="accent",
    noise_variant="street",
    goal="Order Kimchi Jjigae to take away. Confirm your order clearly when asked.",
    caller_name="Stefan Bauer",
    caller_phone="+49 151 22223333",
    caller_address="Schönhauser Allee 55, 10437 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "send_sms"],
),
AudioScenario(
    id="p2-reservation-03",
    phase="phase2",
    category="reservation",
    description="Reservierung für Sonntag 20 Uhr, 6 Personen",
    persona="hard_to_hear",
    noise_variant="restaurant_bg",
    goal="Reserve a table for 6 people on Sunday at 1 PM. Provide name and phone number when asked.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-faq-03",
    phase="phase2",
    category="faq",
    description="Frage zu den Öffnungszeiten am Montag",
    persona="neutral",
    noise_variant="clean",
    turns=[
        ScenarioTurn(user_utterance="Hallo, wann haben Sie montags geöffnet?"),
        ScenarioTurn(user_utterance="Ah, okay, danke für die Info."),
        ScenarioTurn(user_utterance="Nein, das war alles."),
        ScenarioTurn(user_utterance="Dankeschön, tschüss."),
    ],
    expected_tools=[],
),
AudioScenario(
    id="p2-reservation-04",
    phase="phase2",
    category="reservation",
    description="Reservierung für Freitag 19:30 Uhr, 3 Personen",
    persona="impatient",
    noise_variant="street",
    goal="Reserve a table for 4 people this Saturday at 7 PM. Provide your name and phone when asked.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
AudioScenario(
    id="p2-order-06",
    phase="phase2",
    category="order",
    description="Bestellung von Ramyeon zur Lieferung",
    persona="hard_to_hear",
    noise_variant="restaurant_bg",
    goal="Order Tofu Jjigae for home delivery. Give your delivery address and contact details only when the agent asks.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    caller_address="Kastanienallee 7, 10435 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["get_menu", "create_order", "send_sms"],
),
AudioScenario(
    id="p2-reservation-05",
    phase="phase2",
    category="reservation",
    description="Reservierung für Dienstag 18 Uhr, 5 Personen",
    persona="sleepy",
    noise_variant="clean",
    goal="Make a reservation for 3 people on Friday at 6:30 PM. Confirm when asked.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    max_turns=8,
    turns=[],
    expected_tools=["check_availability", "create_reservation"],
),
]
