"""
Additional scenarios for A/B testing:
- 30 Phase 3 (adversarial/complex edge cases)
- 30 Real-Live (full flow: greeting → small talk → FAQ → order → SMS → goodbye)
"""

from dataclasses import field
from server.scenarios.tier2_scenarios import AudioScenario, ScenarioTurn

# ══════════════════════════════════════════════════════════════════════════
# PHASE 3: Adversarial / Complex Edge Cases (30 scenarios)
# These test multi-intent, mid-conversation switches, dialect, confusion,
# and other realistic hard cases that break monolithic prompts.
# ══════════════════════════════════════════════════════════════════════════

PHASE3_SCENARIOS = [
    # --- Multi-intent switches ---
    AudioScenario(
        id="p3-switch-01",
        phase="phase3",
        category="switch",
        description="Starts with order, switches to reservation mid-conversation",
        turns=[
            ScenarioTurn(user_utterance="Ich möchte gerne Bulgogi bestellen"),
            ScenarioTurn(user_utterance="Ach warten Sie, eigentlich möchte ich lieber einen Tisch reservieren"),
            ScenarioTurn(user_utterance="Für Samstag Abend, 4 Personen, um 19 Uhr"),
            ScenarioTurn(user_utterance="Ja, bitte buchen. Name ist Schmidt"),
        ],
        expected_tools=["check_availability", "create_reservation"],
        n_runs=1,
    ),
    AudioScenario(
        id="p3-switch-02",
        phase="phase3",
        category="switch",
        description="Starts with reservation, adds order after",
        turns=[
            ScenarioTurn(user_utterance="Ich hätte gerne einen Tisch für morgen Abend um 20 Uhr, 3 Personen"),
            ScenarioTurn(user_utterance="Ja bitte reservieren, Name Weber"),
            ScenarioTurn(user_utterance="Und können wir auch schon vorbestellen? Dreimal Bibimbap bitte"),
            ScenarioTurn(user_utterance="Meine Nummer ist 0176 44455566"),
        ],
        expected_tools=["check_availability", "create_reservation", "create_order", "send_sms"],
        n_runs=1,
    ),
    AudioScenario(
        id="p3-switch-03",
        phase="phase3",
        category="switch",
        description="Customer changes mind about dish three times",
        turns=[
            ScenarioTurn(user_utterance="Ich nehme ein Bibimbap"),
            ScenarioTurn(user_utterance="Ach nee, doch lieber Bulgogi"),
            ScenarioTurn(user_utterance="Moment, was kostet Kimchi Jjigae?"),
            ScenarioTurn(user_utterance="Ok, dann nehme ich das Kimchi Jjigae bitte"),
            ScenarioTurn(user_utterance="Meine Nummer ist 0221 9998877"),
        ],
        expected_tools=["get_menu", "create_order", "send_sms"],
        n_runs=1,
    ),
    AudioScenario(
        id="p3-switch-04",
        phase="phase3",
        category="switch",
        description="FAQ then suddenly order without browsing menu",
        turns=[
            ScenarioTurn(user_utterance="Haben Sie auch einen Mittagstisch?"),
            ScenarioTurn(user_utterance="Und wie lange habt ihr offen?"),
            ScenarioTurn(user_utterance="Ok, ich nehme schnell ein Bulgogi zum Mitnehmen, Nummer 0176 12345678"),
        ],
        expected_tools=["faq", "create_order", "send_sms"],
        n_runs=1,
    ),
    # --- Impatient / rude but NOT abusive ---
    AudioScenario(
        id="p3-impatient-01",
        phase="phase3",
        category="adversarial",
        description="Impatient customer who wants fast order, no small talk",
        turns=[
            ScenarioTurn(user_utterance="Ja hallo, schnell bitte, ich hab wenig Zeit"),
            ScenarioTurn(user_utterance="Bibimbap, Telefon ist 0176 99988877"),
            ScenarioTurn(user_utterance="Ja stimmt, bestellen"),
        ],
        expected_tools=["create_order", "send_sms"],
        n_runs=1,
    ),
    AudioScenario(
        id="p3-impatient-02",
        phase="phase3",
        category="adversarial",
        description="Customer repeats themselves because bot is too slow",
        turns=[
            ScenarioTurn(user_utterance="Ich möchte bestellen"),
            ScenarioTurn(user_utterance="BESTELLEN habe ich gesagt"),
            ScenarioTurn(user_utterance="Japchae bitte, 0152 11122233"),
        ],
        expected_tools=["create_order", "send_sms"],
        n_runs=1,
    ),
    AudioScenario(
        id="p3-impatient-03",
        phase="phase3",
        category="adversarial",
        description="Customer is annoyed by questions, gives everything at once",
        turns=[
            ScenarioTurn(user_utterance="Ich möchte einen Tisch für Freitag 19 Uhr für 6 Personen auf den Namen Müller, bitte reservieren"),
        ],
        expected_tools=["check_availability", "create_reservation"],
        n_runs=1,
    ),
    # --- Non-menu items ---
    AudioScenario(
        id="p3-nonmenu-01",
        phase="phase3",
        category="tool_edge_case",
        description="Customer orders a dish that doesn't exist on the menu",
        turns=[
            ScenarioTurn(user_utterance="Ich hätte gerne Pad Thai bitte"),
            ScenarioTurn(user_utterance="Dann eben Sushi"),
            ScenarioTurn(user_utterance="Ok was haben Sie denn?"),
            ScenarioTurn(user_utterance="Dann nehme ich Bibimbap, Nummer ist 0221 5556677"),
        ],
        expected_tools=["get_menu", "create_order", "send_sms"],
        n_runs=1,
    ),
    AudioScenario(
        id="p3-nonmenu-02",
        phase="phase3",
        category="tool_edge_case",
        description="Customer insists on non-existent dish, then gives up and orders real one",
        turns=[
            ScenarioTurn(user_utterance="Haben Sie Pizza?"),
            ScenarioTurn(user_utterance="Aber auf der Webseite stand Pizza!"),
            ScenarioTurn(user_utterance="Na gut, was empfehlen Sie denn?"),
            ScenarioTurn(user_utterance="Ok Bulgogi klingt gut, Nummer 0176 33322211"),
        ],
        expected_tools=["get_menu", "create_order", "send_sms"],
        n_runs=1,
    ),
    # --- Large groups / escalation ---
    AudioScenario(
        id="p3-large-01",
        phase="phase3",
        category="adversarial",
        description="Party of 25 should trigger transfer to human",
        turns=[
            ScenarioTurn(user_utterance="Wir planen eine Firmenfeier für 25 Personen"),
            ScenarioTurn(user_utterance="Geht das bei euch?"),
        ],
        expected_tools=["transfer_to_human"],
        n_runs=1,
    ),
    AudioScenario(
        id="p3-large-02",
        phase="phase3",
        category="adversarial",
        description="Starts normal reservation then reveals large group",
        turns=[
            ScenarioTurn(user_utterance="Ich möchte einen Tisch reservieren für nächsten Samstag"),
            ScenarioTurn(user_utterance="Wir sind 30 Leute, geht das?"),
        ],
        expected_tools=["transfer_to_human"],
        n_runs=1,
    ),
    # --- Technical issues ---
    AudioScenario(
        id="p3-tech-01",
        phase="phase3",
        category="tool_edge_case",
        description="App issue complaint",
        turns=[
            ScenarioTurn(user_utterance="Ihre App funktioniert nicht, ich kann nicht bestellen"),
            ScenarioTurn(user_utterance="Ja seit heute Morgen schon"),
        ],
        expected_tools=["technical_issues_callback"],
        n_runs=1,
    ),
    AudioScenario(
        id="p3-tech-02",
        phase="phase3",
        category="tool_edge_case",
        description="Website error then wants to order by phone instead",
        turns=[
            ScenarioTurn(user_utterance="Ihre Webseite zeigt einen Fehler an"),
            ScenarioTurn(user_utterance="Kann ich stattdessen telefonisch bestellen?"),
            ScenarioTurn(user_utterance="Tteokbokki bitte, 0176 77788899"),
        ],
        expected_tools=["technical_issues_callback", "create_order", "send_sms"],
        n_runs=1,
    ),
    # --- Weather + order combo ---
    AudioScenario(
        id="p3-weather-01",
        phase="phase3",
        category="switch",
        description="Asks about weather then decides to order delivery",
        turns=[
            ScenarioTurn(user_utterance="Wie ist das Wetter bei euch in Bonn?"),
            ScenarioTurn(user_utterance="Dann bestelle ich lieber, zum Liefern bitte"),
            ScenarioTurn(user_utterance="Mandu bitte, 0221 4445566"),
        ],
        expected_tools=["get_weather", "create_order", "send_sms"],
        n_runs=1,
    ),
    # --- Abuse handling ---
    AudioScenario(
        id="p3-abuse-01",
        phase="phase3",
        category="adversarial",
        description="Customer starts with insults",
        turns=[
            ScenarioTurn(user_utterance="Was soll der Scheiß, ich warte schon ewig"),
        ],
        expected_tools=["transfer_to_tier2"],
        n_runs=1,
    ),
    AudioScenario(
        id="p3-abuse-02",
        phase="phase3",
        category="adversarial",
        description="Customer insults after long wait, should escalate once",
        turns=[
            ScenarioTurn(user_utterance="Ich habe vor einer Stunde bestellt und nichts ist gekommen"),
            ScenarioTurn(user_utterance="Ihr seid alle Idioten"),
        ],
        expected_tools=["transfer_to_tier2"],
        n_runs=1,
    ),
    # --- Reservation edge cases ---
    AudioScenario(
        id="p3-res-edge-01",
        phase="phase3",
        category="reservation",
        description="Reservation on Monday (Ruhetag) — bot should inform",
        turns=[
            ScenarioTurn(user_utterance="Kann ich für Montag einen Tisch reservieren?"),
            ScenarioTurn(user_utterance="Ach stimmt, dann Dienstag bitte, für 2 um 19 Uhr"),
            ScenarioTurn(user_utterance="Ja bitte reservieren, Name Fischer"),
        ],
        expected_tools=["check_availability", "create_reservation"],
        n_runs=1,
    ),
    AudioScenario(
        id="p3-res-edge-02",
        phase="phase3",
        category="reservation",
        description="Reservation at unusual time — lunch vs dinner ambiguity",
        turns=[
            ScenarioTurn(user_utterance="Haben Sie morgen um 15 Uhr einen Tisch frei?"),
            ScenarioTurn(user_utterance="Ach, um 15 Uhr habt ihr zu? Dann um 18 Uhr bitte, für 3 Personen"),
            ScenarioTurn(user_utterance="Ja bitte, Name König"),
        ],
        expected_tools=["check_availability", "create_reservation"],
        n_runs=1,
    ),
    AudioScenario(
        id="p3-res-edge-03",
        phase="phase3",
        category="reservation",
        description="Customer gives German word numbers instead of digits",
        turns=[
            ScenarioTurn(user_utterance="Einen Tisch für sechs Personen bitte"),
            ScenarioTurn(user_utterance="Am Samstag um halb acht"),
            ScenarioTurn(user_utterance="Ja passt, auf den Namen Braun"),
        ],
        expected_tools=["check_availability", "create_reservation"],
        n_runs=1,
    ),
    # --- Order edge cases ---
    AudioScenario(
        id="p3-ord-edge-01",
        phase="phase3",
        category="order",
        description="Multiple items in one order",
        turns=[
            ScenarioTurn(user_utterance="Ich möchte bestellen: zwei Bibimbap und ein Bulgogi"),
            ScenarioTurn(user_utterance="Meine Nummer ist 0176 55544433"),
            ScenarioTurn(user_utterance="Ja genau, das stimmt"),
        ],
        expected_tools=["create_order", "send_sms"],
        n_runs=1,
    ),
    AudioScenario(
        id="p3-ord-edge-02",
        phase="phase3",
        category="order",
        description="Customer refuses to give phone number, then relents",
        turns=[
            ScenarioTurn(user_utterance="Einmal Japchae bitte"),
            ScenarioTurn(user_utterance="Nein, meine Nummer gebe ich nicht"),
            ScenarioTurn(user_utterance="Ich will keine Nummer angeben"),
            ScenarioTurn(user_utterance="Na gut, 0221 6667788"),
        ],
        expected_tools=["create_order", "send_sms"],
        n_runs=1,
    ),
    AudioScenario(
        id="p3-ord-edge-03",
        phase="phase3",
        category="order",
        description="Customer orders Mochi-Eis only (dessert order)",
        turns=[
            ScenarioTurn(user_utterance="Kann man bei euch auch nur Nachtisch bestellen?"),
            ScenarioTurn(user_utterance="Dann hätte ich gerne Mochi-Eis"),
            ScenarioTurn(user_utterance="0176 22233344"),
        ],
        expected_tools=["create_order", "send_sms"],
        n_runs=1,
    ),
    # --- FAQ-heavy ---
    AudioScenario(
        id="p3-faq-01",
        phase="phase3",
        category="instruction",
        description="Multiple FAQ questions in a row",
        turns=[
            ScenarioTurn(user_utterance="Wo ist das Restaurant genau?"),
            ScenarioTurn(user_utterance="Gibt es Parkplätze in der Nähe?"),
            ScenarioTurn(user_utterance="Kann man auch bar bezahlen?"),
            ScenarioTurn(user_utterance="Danke, das wars, tschüss"),
        ],
        expected_tools=["faq", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="p3-faq-02",
        phase="phase3",
        category="instruction",
        description="Allergen questions then order",
        turns=[
            ScenarioTurn(user_utterance="Ich habe eine Glutenunverträglichkeit, was kann ich bei euch essen?"),
            ScenarioTurn(user_utterance="Ist das Bibimbap glutenfrei?"),
            ScenarioTurn(user_utterance="Ok dann bestelle ich das Tofu Bibimbap, 0152 99988877"),
        ],
        expected_tools=["get_menu", "create_order", "send_sms"],
        n_runs=1,
    ),
    # --- Confused / unclear intent ---
    AudioScenario(
        id="p3-confused-01",
        phase="phase3",
        category="adversarial",
        description="Customer is unsure what they want",
        turns=[
            ScenarioTurn(user_utterance="Ähmm, ja hallo"),
            ScenarioTurn(user_utterance="Ich weiß nicht genau, was kann man bei euch so machen?"),
            ScenarioTurn(user_utterance="Was empfehlen Sie denn?"),
            ScenarioTurn(user_utterance="Ok dann das Bulgogi zum Mitnehmen bitte, 0176 11100099"),
        ],
        expected_tools=["get_menu", "create_order", "send_sms"],
        n_runs=1,
    ),
    AudioScenario(
        id="p3-confused-02",
        phase="phase3",
        category="adversarial",
        description="Customer gives contradictory info",
        turns=[
            ScenarioTurn(user_utterance="Ich möchte bestellen und auch reservieren"),
            ScenarioTurn(user_utterance="Erstmal die Bestellung: Kimchi Jjigae, 0221 4443322"),
            ScenarioTurn(user_utterance="Ja genau bestellen"),
            ScenarioTurn(user_utterance="Und dann noch einen Tisch für Samstag 20 Uhr, 2 Personen"),
            ScenarioTurn(user_utterance="Ja bitte reservieren, Name Bauer"),
        ],
        expected_tools=["create_order", "send_sms", "check_availability", "create_reservation"],
        n_runs=1,
    ),
    # --- Dialect / informal speech ---
    AudioScenario(
        id="p3-dialect-01",
        phase="phase3",
        category="adversarial",
        description="Informal/casual speech style",
        turns=[
            ScenarioTurn(user_utterance="Hey, kann ich was bestellen?"),
            ScenarioTurn(user_utterance="Gib mir mal nen Bulgogi, Nummer ist null eins sieben sechs fünf fünf fünf vier vier drei drei"),
        ],
        expected_tools=["create_order", "send_sms"],
        n_runs=1,
    ),
    AudioScenario(
        id="p3-dialect-02",
        phase="phase3",
        category="adversarial",
        description="Elderly person, slow, repeats themselves",
        turns=[
            ScenarioTurn(user_utterance="Ja hallo, ich möchte gerne... ähm... einen Tisch bestellen, ach nein reservieren meine ich"),
            ScenarioTurn(user_utterance="Für zwei Personen, meine Frau und ich"),
            ScenarioTurn(user_utterance="Am Samstag wäre schön, so gegen 18 Uhr"),
            ScenarioTurn(user_utterance="Ja das wäre fein, auf den Namen Hoffmann"),
        ],
        expected_tools=["check_availability", "create_reservation"],
        n_runs=1,
    ),
    AudioScenario(
        id="p3-rapid-01",
        phase="phase3",
        category="adversarial",
        description="Rapid-fire customer dumps everything at once",
        turns=[
            ScenarioTurn(user_utterance="Tofu Jjigae zum Mitnehmen bitte, Nummer null eins fünf zwei drei drei vier vier fünf fünf sechs sechs"),
            ScenarioTurn(user_utterance="Ja stimmt so, danke"),
        ],
        expected_tools=["create_order", "send_sms"],
        n_runs=1,
    ),
    AudioScenario(
        id="p3-cancel-01",
        phase="phase3",
        category="adversarial",
        description="Customer starts ordering then cancels everything",
        turns=[
            ScenarioTurn(user_utterance="Ich möchte ein Bibimbap bestellen"),
            ScenarioTurn(user_utterance="Ach nee, doch nicht, vergessen Sie es"),
            ScenarioTurn(user_utterance="Tschüss"),
        ],
        expected_tools=["end_call"],
        n_runs=1,
    ),
]


# ══════════════════════════════════════════════════════════════════════════
# REAL-LIVE SCENARIOS: Full end-to-end flow (30 scenarios)
# greeting → small talk → FAQ → order/reservation → confirmation → goodbye
# These simulate realistic complete phone calls with natural conversation flow.
# ══════════════════════════════════════════════════════════════════════════

REAL_LIVE_SCENARIOS = [
    # --- Complete order flows ---
    AudioScenario(
        id="rl-order-01",
        phase="real_live",
        category="order",
        description="Full flow: greeting, menu question, order Bibimbap, phone, confirm, SMS, goodbye",
        turns=[
            ScenarioTurn(user_utterance="Hallo, guten Abend"),
            ScenarioTurn(user_utterance="Was haben Sie denn auf der Karte?"),
            ScenarioTurn(user_utterance="Das Bibimbap klingt gut, das nehme ich"),
            ScenarioTurn(user_utterance="Meine Telefonnummer ist 0176 12345678"),
            ScenarioTurn(user_utterance="Ja genau, das stimmt so"),
            ScenarioTurn(user_utterance="Wie lange dauert die Lieferung ungefähr?"),
            ScenarioTurn(user_utterance="Super, vielen Dank. Auf Wiedersehen!"),
        ],
        expected_tools=["get_menu", "create_order", "send_sms", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-order-02",
        phase="real_live",
        category="order",
        description="Full flow: greeting, small talk about opening hours, then Bulgogi order",
        turns=[
            ScenarioTurn(user_utterance="Guten Tag, hier ist Frau Meier"),
            ScenarioTurn(user_utterance="Haben Sie heute noch offen?"),
            ScenarioTurn(user_utterance="Sehr gut. Ich möchte gerne bestellen"),
            ScenarioTurn(user_utterance="Einmal Bulgogi bitte"),
            ScenarioTurn(user_utterance="Ja, meine Nummer ist 0221 9876543"),
            ScenarioTurn(user_utterance="Das stimmt, bitte bestellen"),
            ScenarioTurn(user_utterance="Danke schön, bis dann!"),
        ],
        expected_tools=["create_order", "send_sms", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-order-03",
        phase="real_live",
        category="order",
        description="Full flow: greeting, asks about vegetarian options, orders Tofu Bibimbap",
        turns=[
            ScenarioTurn(user_utterance="Hallo, ich bin Vegetarierin"),
            ScenarioTurn(user_utterance="Was haben Sie denn Vegetarisches?"),
            ScenarioTurn(user_utterance="Das Tofu Bibimbap klingt gut"),
            ScenarioTurn(user_utterance="Ja bitte bestellen, meine Nummer ist 0152 33344455"),
            ScenarioTurn(user_utterance="Stimmt so, danke"),
            ScenarioTurn(user_utterance="Tschüss!"),
        ],
        expected_tools=["get_menu", "create_order", "send_sms", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-order-04",
        phase="real_live",
        category="order",
        description="Full flow: delivery address question, Kimchi Jjigae order",
        turns=[
            ScenarioTurn(user_utterance="Hallo, liefern Sie auch nach Beuel?"),
            ScenarioTurn(user_utterance="Super, dann bestelle ich gerne"),
            ScenarioTurn(user_utterance="Einmal Kimchi Jjigae bitte"),
            ScenarioTurn(user_utterance="0176 55566677"),
            ScenarioTurn(user_utterance="Ja genau"),
            ScenarioTurn(user_utterance="Vielen Dank, auf Wiedersehen"),
        ],
        expected_tools=["faq", "create_order", "send_sms", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-order-05",
        phase="real_live",
        category="order",
        description="Full flow: Japchae order with price question",
        turns=[
            ScenarioTurn(user_utterance="Guten Abend, was kostet das Japchae?"),
            ScenarioTurn(user_utterance="Ok, das nehme ich bitte"),
            ScenarioTurn(user_utterance="Nummer ist 0221 1112233"),
            ScenarioTurn(user_utterance="Ja passt"),
            ScenarioTurn(user_utterance="Danke, tschüss"),
        ],
        expected_tools=["get_menu", "create_order", "send_sms", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-order-06",
        phase="real_live",
        category="order",
        description="Full flow: Mandu order, asks about delivery time",
        turns=[
            ScenarioTurn(user_utterance="Hallo, ich möchte gerne Mandu bestellen"),
            ScenarioTurn(user_utterance="Wie lange dauert die Lieferung?"),
            ScenarioTurn(user_utterance="Ja ok, Telefonnummer 0176 44433322"),
            ScenarioTurn(user_utterance="Ja stimmt so"),
            ScenarioTurn(user_utterance="Danke schön, auf Wiederhören"),
        ],
        expected_tools=["create_order", "send_sms", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-order-07",
        phase="real_live",
        category="order",
        description="Full flow: Tteokbokki, customer confirms after summary",
        turns=[
            ScenarioTurn(user_utterance="Guten Tag"),
            ScenarioTurn(user_utterance="Ich hätte gerne Tteokbokki zum Mitnehmen"),
            ScenarioTurn(user_utterance="0152 77788899"),
            ScenarioTurn(user_utterance="Ja genau, bestellen bitte"),
            ScenarioTurn(user_utterance="Super vielen Dank, tschüss!"),
        ],
        expected_tools=["create_order", "send_sms", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-order-08",
        phase="real_live",
        category="order",
        description="Full flow: browses menu, picks Tofu Jjigae",
        turns=[
            ScenarioTurn(user_utterance="Hallo, können Sie mir die Speisekarte vorlesen?"),
            ScenarioTurn(user_utterance="Was ist Tofu Jjigae genau?"),
            ScenarioTurn(user_utterance="Das nehme ich, meine Nummer ist 0176 88877766"),
            ScenarioTurn(user_utterance="Ja das passt so"),
            ScenarioTurn(user_utterance="Danke, auf Wiedersehen!"),
        ],
        expected_tools=["get_menu", "create_order", "send_sms", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-order-09",
        phase="real_live",
        category="order",
        description="Full flow: address question, then Mochi-Eis order",
        turns=[
            ScenarioTurn(user_utterance="Hallo, wo genau ist das Restaurant?"),
            ScenarioTurn(user_utterance="Ah Bornheimer Straße, gut zu wissen"),
            ScenarioTurn(user_utterance="Kann ich auch nur ein Dessert bestellen? Mochi-Eis bitte"),
            ScenarioTurn(user_utterance="0221 3334455"),
            ScenarioTurn(user_utterance="Ja bitte"),
            ScenarioTurn(user_utterance="Danke, bis gleich!"),
        ],
        expected_tools=["create_order", "send_sms", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-order-10",
        phase="real_live",
        category="order",
        description="Full flow: asks about Korean food, then orders confidently",
        turns=[
            ScenarioTurn(user_utterance="Guten Abend, ich war noch nie koreanisch essen"),
            ScenarioTurn(user_utterance="Was würden Sie einem Anfänger empfehlen?"),
            ScenarioTurn(user_utterance="Bibimbap klingt gut, das probiere ich"),
            ScenarioTurn(user_utterance="Nummer ist 0176 22211100"),
            ScenarioTurn(user_utterance="Ja genau so"),
            ScenarioTurn(user_utterance="Vielen Dank für die Beratung, tschüss!"),
        ],
        expected_tools=["get_menu", "create_order", "send_sms", "end_call"],
        n_runs=1,
    ),
    # --- Complete reservation flows ---
    AudioScenario(
        id="rl-res-01",
        phase="real_live",
        category="reservation",
        description="Full flow: greeting, small talk, reserve for dinner",
        turns=[
            ScenarioTurn(user_utterance="Guten Tag, ich plane ein Geburtstagsessen"),
            ScenarioTurn(user_utterance="Haben Sie am Samstag Abend noch Platz?"),
            ScenarioTurn(user_utterance="Für 6 Personen, um 19 Uhr"),
            ScenarioTurn(user_utterance="Ja bitte buchen, Name Schneider"),
            ScenarioTurn(user_utterance="Wunderbar, vielen Dank!"),
            ScenarioTurn(user_utterance="Auf Wiedersehen!"),
        ],
        expected_tools=["check_availability", "create_reservation", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-res-02",
        phase="real_live",
        category="reservation",
        description="Full flow: asks about opening hours first, then reserves",
        turns=[
            ScenarioTurn(user_utterance="Hallo, wann haben Sie abends geöffnet?"),
            ScenarioTurn(user_utterance="Gut, dann möchte ich gerne einen Tisch reservieren"),
            ScenarioTurn(user_utterance="Morgen um 20 Uhr für 2 Personen"),
            ScenarioTurn(user_utterance="Ja bitte, auf den Namen Klein"),
            ScenarioTurn(user_utterance="Danke schön, bis morgen!"),
        ],
        expected_tools=["check_availability", "create_reservation", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-res-03",
        phase="real_live",
        category="reservation",
        description="Full flow: lunch reservation",
        turns=[
            ScenarioTurn(user_utterance="Guten Morgen, kann man bei Ihnen auch mittags reservieren?"),
            ScenarioTurn(user_utterance="Für Dienstag 12:30 Uhr, 4 Personen"),
            ScenarioTurn(user_utterance="Name ist Wolf"),
            ScenarioTurn(user_utterance="Ja bitte reservieren"),
            ScenarioTurn(user_utterance="Vielen Dank, auf Wiederhören"),
        ],
        expected_tools=["check_availability", "create_reservation", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-res-04",
        phase="real_live",
        category="reservation",
        description="Full flow: romantic dinner for 2",
        turns=[
            ScenarioTurn(user_utterance="Hallo, ich möchte meiner Frau zum Hochzeitstag ein Abendessen schenken"),
            ScenarioTurn(user_utterance="Haben Sie am Freitagabend einen schönen Tisch für 2?"),
            ScenarioTurn(user_utterance="Um 19:30 wäre perfekt"),
            ScenarioTurn(user_utterance="Ja bitte buchen, Name Lehmann"),
            ScenarioTurn(user_utterance="Wunderbar, vielen herzlichen Dank"),
            ScenarioTurn(user_utterance="Auf Wiedersehen!"),
        ],
        expected_tools=["check_availability", "create_reservation", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-res-05",
        phase="real_live",
        category="reservation",
        description="Full flow: weekend brunch reservation",
        turns=[
            ScenarioTurn(user_utterance="Guten Tag, haben Sie am Sonntag Mittag geöffnet?"),
            ScenarioTurn(user_utterance="Wir sind zu dritt und würden gerne um 12 Uhr kommen"),
            ScenarioTurn(user_utterance="Ja genau, Name Beck"),
            ScenarioTurn(user_utterance="Tschüss, danke!"),
        ],
        expected_tools=["check_availability", "create_reservation", "end_call"],
        n_runs=1,
    ),
    # --- Mixed flows (order + reservation + FAQ) ---
    AudioScenario(
        id="rl-mixed-01",
        phase="real_live",
        category="order",
        description="Full flow: FAQ about location, then order for pickup",
        turns=[
            ScenarioTurn(user_utterance="Hallo, wo genau seid ihr? Bornheimer Straße?"),
            ScenarioTurn(user_utterance="Ok, dann komme ich vorbei und hole ab"),
            ScenarioTurn(user_utterance="Ein Bulgogi zum Abholen bitte"),
            ScenarioTurn(user_utterance="0176 44455566"),
            ScenarioTurn(user_utterance="Ja bestellen bitte"),
            ScenarioTurn(user_utterance="Bin in 20 Minuten da, danke!"),
        ],
        expected_tools=["create_order", "send_sms", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-mixed-02",
        phase="real_live",
        category="order",
        description="Full flow: menu inquiry, allergy question, careful order",
        turns=[
            ScenarioTurn(user_utterance="Guten Abend, ich habe eine Frage zum Menü"),
            ScenarioTurn(user_utterance="Welche Gerichte sind denn vegan?"),
            ScenarioTurn(user_utterance="Ist das Japchae vegan?"),
            ScenarioTurn(user_utterance="Ok, dann nehme ich Japchae bitte"),
            ScenarioTurn(user_utterance="0152 66677788"),
            ScenarioTurn(user_utterance="Ja stimmt so"),
            ScenarioTurn(user_utterance="Vielen Dank, auf Wiedersehen"),
        ],
        expected_tools=["get_menu", "create_order", "send_sms", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-mixed-03",
        phase="real_live",
        category="reservation",
        description="Full flow: asks about restaurant, then reserves",
        turns=[
            ScenarioTurn(user_utterance="Hallo, was für ein Restaurant sind Sie genau?"),
            ScenarioTurn(user_utterance="Koreanisch, interessant! Kann man bei Ihnen reservieren?"),
            ScenarioTurn(user_utterance="Für Donnerstag um 19 Uhr, 5 Personen"),
            ScenarioTurn(user_utterance="Ja bitte, Name Hartmann"),
            ScenarioTurn(user_utterance="Danke, wir freuen uns!"),
        ],
        expected_tools=["faq", "check_availability", "create_reservation", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-mixed-04",
        phase="real_live",
        category="order",
        description="Full flow: delivery time question, then quick order",
        turns=[
            ScenarioTurn(user_utterance="Hallo, wie lange dauert eine Lieferung zu mir nach Poppelsdorf?"),
            ScenarioTurn(user_utterance="Ok das geht. Einmal Tteokbokki bitte"),
            ScenarioTurn(user_utterance="0221 7778899"),
            ScenarioTurn(user_utterance="Ja, bestellen bitte"),
            ScenarioTurn(user_utterance="Danke!"),
        ],
        expected_tools=["create_order", "send_sms", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-mixed-05",
        phase="real_live",
        category="order",
        description="Full flow: repeat customer, knows what they want",
        turns=[
            ScenarioTurn(user_utterance="Hallo Sailly, ich bin es wieder"),
            ScenarioTurn(user_utterance="Das Übliche bitte, ein Bibimbap"),
            ScenarioTurn(user_utterance="Nummer ist immer noch 0176 99900011"),
            ScenarioTurn(user_utterance="Genau, bestellen"),
            ScenarioTurn(user_utterance="Danke wie immer, tschüss!"),
        ],
        expected_tools=["create_order", "send_sms", "end_call"],
        n_runs=1,
    ),
    # --- FAQ-only flows ---
    AudioScenario(
        id="rl-faq-01",
        phase="real_live",
        category="instruction",
        description="Full flow: just wants info, no order or reservation",
        turns=[
            ScenarioTurn(user_utterance="Hallo, haben Sie am Sonntag offen?"),
            ScenarioTurn(user_utterance="Und bis wie viel Uhr abends?"),
            ScenarioTurn(user_utterance="Kann man auch ohne Reservierung kommen?"),
            ScenarioTurn(user_utterance="Gut zu wissen, danke. Auf Wiedersehen!"),
        ],
        expected_tools=["faq", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-faq-02",
        phase="real_live",
        category="instruction",
        description="Full flow: wants directions and parking info",
        turns=[
            ScenarioTurn(user_utterance="Hallo, ich suche Ihr Restaurant"),
            ScenarioTurn(user_utterance="In welcher Straße sind Sie nochmal?"),
            ScenarioTurn(user_utterance="Gibt es Parkplätze in der Nähe?"),
            ScenarioTurn(user_utterance="Super, dann kommen wir vorbei. Danke!"),
        ],
        expected_tools=["faq", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-faq-03",
        phase="real_live",
        category="instruction",
        description="Full flow: wants to know about the restaurant concept",
        turns=[
            ScenarioTurn(user_utterance="Guten Tag, was genau ist DOBOO für ein Restaurant?"),
            ScenarioTurn(user_utterance="Koreanische Küche, aha. Ist das scharf?"),
            ScenarioTurn(user_utterance="Danke für die Info, ich überlege noch. Tschüss!"),
        ],
        expected_tools=["faq", "end_call"],
        n_runs=1,
    ),
    # --- Order then immediate goodbye ---
    AudioScenario(
        id="rl-quick-01",
        phase="real_live",
        category="order",
        description="Full flow: fastest possible order, no small talk",
        turns=[
            ScenarioTurn(user_utterance="Bibimbap, 0176 11122233, bestellen bitte"),
            ScenarioTurn(user_utterance="Ja genau"),
            ScenarioTurn(user_utterance="Danke, tschüss"),
        ],
        expected_tools=["create_order", "send_sms", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-quick-02",
        phase="real_live",
        category="reservation",
        description="Full flow: fast reservation, all info at once",
        turns=[
            ScenarioTurn(user_utterance="Tisch für 4, Samstag 19 Uhr, Name Schulz"),
            ScenarioTurn(user_utterance="Ja bitte buchen"),
            ScenarioTurn(user_utterance="Danke!"),
        ],
        expected_tools=["check_availability", "create_reservation", "end_call"],
        n_runs=1,
    ),
    # --- Greeting recognized properly ---
    AudioScenario(
        id="rl-greet-01",
        phase="real_live",
        category="instruction",
        description="Full flow: just calls to say hi and ask about hours",
        turns=[
            ScenarioTurn(user_utterance="Guten Tag"),
            ScenarioTurn(user_utterance="Wann haben Sie denn offen?"),
            ScenarioTurn(user_utterance="Auch am Wochenende?"),
            ScenarioTurn(user_utterance="Gut, danke schön. Auf Wiedersehen!"),
        ],
        expected_tools=["end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-greet-02",
        phase="real_live",
        category="instruction",
        description="Full flow: polite greeting, weather chitchat, then leaves",
        turns=[
            ScenarioTurn(user_utterance="Hallo, schönen guten Abend"),
            ScenarioTurn(user_utterance="Wie ist das Wetter bei euch in Bonn?"),
            ScenarioTurn(user_utterance="Ah interessant. Na dann vielleicht ein anderes Mal. Tschüss!"),
        ],
        expected_tools=["get_weather", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-order-11",
        phase="real_live",
        category="order",
        description="Full flow: customer knows exactly what they want, minimal turns",
        turns=[
            ScenarioTurn(user_utterance="Guten Abend, ich hätte gerne Bulgogi zum Liefern"),
            ScenarioTurn(user_utterance="Meine Nummer ist 0176 66677788"),
            ScenarioTurn(user_utterance="Ja passt so, bitte bestellen"),
            ScenarioTurn(user_utterance="Vielen Dank, tschüss!"),
        ],
        expected_tools=["create_order", "send_sms", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-res-06",
        phase="real_live",
        category="reservation",
        description="Full flow: family dinner reservation with kids",
        turns=[
            ScenarioTurn(user_utterance="Hallo, wir möchten gerne mit unseren Kindern essen kommen"),
            ScenarioTurn(user_utterance="Haben Sie am Sonntagmittag einen Tisch für 5?"),
            ScenarioTurn(user_utterance="Um 12 Uhr wäre perfekt"),
            ScenarioTurn(user_utterance="Ja bitte, Name Meyer"),
            ScenarioTurn(user_utterance="Toll, danke. Auf Wiedersehen!"),
        ],
        expected_tools=["check_availability", "create_reservation", "end_call"],
        n_runs=1,
    ),
    AudioScenario(
        id="rl-mixed-06",
        phase="real_live",
        category="order",
        description="Full flow: opening hours, menu browse, order with full confirmation",
        turns=[
            ScenarioTurn(user_utterance="Guten Abend, haben Sie jetzt noch offen?"),
            ScenarioTurn(user_utterance="Können Sie mir die Karte zeigen?"),
            ScenarioTurn(user_utterance="Was ist denn Tteokbokki genau?"),
            ScenarioTurn(user_utterance="Klingt gut, das bestelle ich bitte"),
            ScenarioTurn(user_utterance="0152 44455566"),
            ScenarioTurn(user_utterance="Ja genau so, bitte bestellen"),
            ScenarioTurn(user_utterance="Danke schön, guten Abend noch!"),
        ],
        expected_tools=["get_menu", "create_order", "send_sms", "end_call"],
        n_runs=1,
    ),
]

# Combined list
AB_TEST_EXTRA_SCENARIOS = PHASE3_SCENARIOS + REAL_LIVE_SCENARIOS
