"""
Phase 3 — Chaos & Multi-Intent — Scenarios

Rebuilt by server/training/rebuild_scenarios.py (deduplicated + enriched with caller data).
"""

from server.scenarios.base import AudioScenario, ScenarioTurn

PHASE3_SCENARIOS = [
AudioScenario(
    id="p3-chaos-01",
    phase="phase3",
    category="chaos",
    description="Mehrfach Meinungsänderung bei Bestellung",
    persona="chaos",
    noise_variant="restaurant_bg",
    goal="First try to order Bibimbap, then change your mind and want Tteokbokki instead, then finally decide to order Bibimbap for delivery. Provide details only when asked.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    caller_address="Berliner Str. 42, 10115 Berlin",
    max_turns=10,
    turns=[],
    expected_tools=["ai_greeting", "create_order", "verify_address"],
),
AudioScenario(
    id="p3-accent-02",
    phase="phase3",
    category="accent",
    description="Lieferung, dann doch Reservierung, unsicher",
    persona="accent",
    noise_variant="street",
    goal="Order Bulgogi for home delivery. Give your delivery address and contact details only when the agent asks.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    caller_address="Friedrichstr. 18, 10117 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_reservation", "create_order"],
),
AudioScenario(
    id="p3-sleepy-03",
    phase="phase3",
    category="sleepy",
    description="Reservierung, dann Essen, dann Rückruf",
    persona="sleepy",
    noise_variant="clean",
    goal="Order Kimchi Jjigae to take away. Confirm your order clearly when asked.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    caller_address="Kastanienallee 7, 10435 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_order"],
),
AudioScenario(
    id="p3-impatient-04",
    phase="phase3",
    category="impatient",
    description="Schnelle FAQ-Fragen und Reservierung",
    persona="impatient",
    noise_variant="speakerphone",
    goal="Order Tteokbokki for delivery. You are in a hurry but provide all required details when asked.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    caller_address="Karl-Marx-Allee 101, 10243 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_reservation", "get_date_info"],
),
AudioScenario(
    id="p3-angry-05",
    phase="phase3",
    category="angry",
    description="Beschwert sich über Öffnungszeiten und Bestellung",
    persona="angry",
    noise_variant="restaurant_bg",
    goal="Order Japchae for delivery. Be polite but brief.",
    caller_name="Stefan Bauer",
    caller_phone="+49 151 22223333",
    caller_address="Schönhauser Allee 55, 10437 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_order", "verify_address"],
),
AudioScenario(
    id="p3-chaos-06",
    phase="phase3",
    category="chaos",
    description="Wechselt von Reserve zu FAQ zu Bestellung",
    persona="chaos",
    noise_variant="clean",
    goal="First try to order Mandu, then change your mind and want Bibimbap instead, then finally decide to order Mandu for delivery. Provide details only when asked.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    caller_address="Prenzlauer Allee 12, 10405 Berlin",
    max_turns=10,
    turns=[],
    expected_tools=["ai_greeting", "create_order", "verify_address"],
),
AudioScenario(
    id="p3-accent-07",
    phase="phase3",
    category="accent",
    description="Unklare Bestellung mit Rückfragen",
    persona="accent",
    noise_variant="street",
    goal="Order Tofu Jjigae for home delivery. Give your delivery address and contact details only when the agent asks.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    caller_address="Berliner Str. 42, 10115 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_order", "verify_address"],
),
AudioScenario(
    id="p3-sleepy-08",
    phase="phase3",
    category="sleepy",
    description="Langsame Bestellung, dann Reservierung",
    persona="sleepy",
    noise_variant="speakerphone",
    goal="Order Tofu Bibimbap to take away. Confirm your order clearly when asked.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    caller_address="Friedrichstr. 18, 10117 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_reservation", "get_date_info"],
),
AudioScenario(
    id="p3-reservation-04",
    phase="phase3",
    category="reservation",
    description="Reservierung für 4 Personen, dann Änderung",
    persona="chaos",
    noise_variant="restaurant_bg",
    goal="Reserve a table for 6 people on Sunday at 1 PM. Provide name and phone number when asked.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    max_turns=8,
    turns=[],
    expected_tools=["create_reservation"],
),
AudioScenario(
    id="p3-order-04",
    phase="phase3",
    category="order",
    description="Wechselt zwischen Abholung und Lieferung",
    persona="accent",
    noise_variant="clean",
    goal="Order Bulgogi for delivery. Be polite but brief.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    caller_address="Karl-Marx-Allee 101, 10243 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["create_order", "verify_address"],
),
AudioScenario(
    id="p3-faq-04",
    phase="phase3",
    category="faq",
    description="Fragen zur Bezahlung, dann Reservierung",
    persona="angry",
    noise_variant="street",
    turns=[
        ScenarioTurn(user_utterance="Hallo, ich frage mich, warum kein PayPal?"),
        ScenarioTurn(user_utterance="Das ist echt unpraktisch! Also, wie kann ich bezahlen?"),
        ScenarioTurn(user_utterance="Na gut, Barzahlung geht also... Ist reservieren möglich?"),
        ScenarioTurn(user_utterance="Für Sonntag, 20 Uhr, 3 Leute."),
        ScenarioTurn(user_utterance="Mein Nachname ist Schmidt. Telefonnummer ist 0172 5555555."),
        ScenarioTurn(user_utterance="Also ist das nun alles klar?"),
        ScenarioTurn(user_utterance="Ja, richtig. Danke trotzdem."),
        ScenarioTurn(user_utterance="Tschüss."),
    ],
    expected_tools=["create_reservation"],
),
AudioScenario(
    id="p3-order-05",
    phase="phase3",
    category="order",
    description="Bestellung von Ramyeon, mehrfach geändert",
    persona="chaos",
    noise_variant="speakerphone",
    goal="Order Tteokbokki for home delivery. Give your delivery address and contact details only when the agent asks.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    caller_address="Prenzlauer Allee 12, 10405 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["create_order", "verify_address"],
),
AudioScenario(
    id="p3-faq-05",
    phase="phase3",
    category="faq",
    description="Fragen zu Kimchi, dann Reservierung",
    persona="sleepy",
    noise_variant="clean",
    turns=[
        ScenarioTurn(user_utterance="Hallo... Ich wollte wissen, was Kimchi... ähm... genau ist."),
        ScenarioTurn(user_utterance="Ach so, dann könnte ich... es mal probieren..."),
        ScenarioTurn(user_utterance="Vielleicht reservieren für morgen... Abend."),
        ScenarioTurn(user_utterance="Für zwei Personen... 19 Uhr oder so."),
        ScenarioTurn(user_utterance="Name ist Bauer... Telefon 0151... oh... 9876543."),
        ScenarioTurn(user_utterance="Ja... genau... danke..."),
        ScenarioTurn(user_utterance="Okay... auf wiederhören."),
    ],
    expected_tools=["create_reservation"],
),
AudioScenario(
    id="p3-order-06",
    phase="phase3",
    category="order",
    description="Kimbap-Bestellung mit abweichenden Adressen",
    persona="angry",
    noise_variant="restaurant_bg",
    goal="Order Mandu for delivery. You are in a hurry but provide all required details when asked.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    caller_address="Friedrichstr. 18, 10117 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["create_order", "verify_address"],
),
AudioScenario(
    id="p3-reservation-05",
    phase="phase3",
    category="reservation",
    description="Reservierung an verschiedenen Tagen",
    persona="accent",
    noise_variant="street",
    goal="Book a table for 2 for tomorrow evening at 7:30 PM. Answer all questions clearly.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    max_turns=8,
    turns=[],
    expected_tools=["create_reservation"],
),
AudioScenario(
    id="p3-faq-06",
    phase="phase3",
    category="faq",
    description="Parkplatzfrage, dann Essensbestellung",
    persona="sleepy",
    noise_variant="speakerphone",
    turns=[
        ScenarioTurn(user_utterance="Hallo... Gibt's... Parkplätze... bei DOBOO?"),
        ScenarioTurn(user_utterance="Rheinufer-Parkhaus... okay... 200 Meter... entfernt..."),
        ScenarioTurn(user_utterance="Vielleicht... Bibimbap bestellen..."),
        ScenarioTurn(user_utterance="Ja... Bibimbap... geliefert..."),
        ScenarioTurn(user_utterance="Anstraße 30... oder... war's... Anstraße 35..."),
        ScenarioTurn(user_utterance="Telefon... 0170... 5556789..."),
        ScenarioTurn(user_utterance="Ja... das... stimmt..."),
        ScenarioTurn(user_utterance="Okay... Auf... Wiederhören..."),
    ],
    expected_tools=["create_order", "verify_address"],
),
AudioScenario(
    id="p3-order-005",
    phase="phase3",
    category="order",
    description="Anrufer ändert Gericht und fragt über Parkmöglichkeiten",
    persona="chaos",
    noise_variant="restaurant_bg",
    goal="Order Bibimbap for home delivery. Give your delivery address and contact details only when the agent asks.",
    caller_name="Stefan Bauer",
    caller_phone="+49 151 22223333",
    caller_address="Schönhauser Allee 55, 10437 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "get_menu", "verify_address", "create_order"],
),
AudioScenario(
    id="p3-reservation-006",
    phase="phase3",
    category="reservation",
    description="Reservierung und Menüfragen mit Meinungsänderung",
    persona="chaos",
    noise_variant="clean",
    goal="Make a reservation for 3 people on Friday at 6:30 PM. Confirm when asked.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_reservation", "get_menu"],
),
AudioScenario(
    id="p3-faq-007",
    phase="phase3",
    category="faq",
    description="Fragen über Zahlungsmethoden und Öffnungszeiten",
    persona="impatient",
    noise_variant="speakerphone",
    turns=[
        ScenarioTurn(user_utterance="Hallo, welche Zahlungsmethoden akzeptiert ihr?"),
        ScenarioTurn(user_utterance="Und... wie sind die Öffnungszeiten? Schnell bitte."),
        ScenarioTurn(user_utterance="Oh, Montag auch?"),
        ScenarioTurn(user_utterance="Hmpf... Kann ich um 13 Uhr heute bestellen? Ist spät?"),
    ],
    expected_tools=["ai_greeting", "get_date_info"],
),
AudioScenario(
    id="p3-order-008",
    phase="phase3",
    category="order",
    description="Anrufer fragt Lieferbereich und ändert Bestellung",
    persona="accent",
    noise_variant="street",
    goal="Order Tteokbokki for delivery. Be polite but brief.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    caller_address="Friedrichstr. 18, 10117 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_order", "verify_address"],
),
AudioScenario(
    id="p3-faq-009",
    phase="phase3",
    category="faq",
    description="Anrufer ist aufgrund Zahlungsmethoden verwirrt",
    persona="chaos",
    noise_variant="restaurant_bg",
    turns=[
        ScenarioTurn(user_utterance="Hallo, wie kann ich bei euch zahlen?"),
        ScenarioTurn(user_utterance="Aber kein PayPal, oder? Äh, und wann macht ihr auf?"),
        ScenarioTurn(user_utterance="Äh, okay. Und Montag auch? War da nicht irgendwas?"),
        ScenarioTurn(user_utterance="Oh ja, stimmt. Gut, danke."),
        ScenarioTurn(user_utterance="Tschüss."),
    ],
    expected_tools=["ai_greeting", "get_date_info"],
),
AudioScenario(
    id="p3-reservation-010",
    phase="phase3",
    category="reservation",
    description="Reservierung mit unsicherer Uhrzeit und Nachfrage",
    persona="sleepy",
    noise_variant="clean",
    goal="Book a table for 2 people tonight at 8 PM. Give your contact details when the agent asks.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_reservation", "get_menu"],
),
AudioScenario(
    id="p3-order-011",
    phase="phase3",
    category="order",
    description="Anrufer ändert ständig Bestellmenü",
    persona="chaos",
    noise_variant="street",
    goal="Order Tofu Jjigae to take away. Confirm your order clearly when asked.",
    caller_name="Stefan Bauer",
    caller_phone="+49 151 22223333",
    caller_address="Schönhauser Allee 55, 10437 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_order", "verify_address"],
),
AudioScenario(
    id="p3-faq-012",
    phase="phase3",
    category="faq",
    description="Fragt chaotisch über Speisekarte und Öffnungszeiten",
    persona="angry",
    noise_variant="restaurant_bg",
    turns=[
        ScenarioTurn(user_utterance="Hallo, was gibt's heute auf dem Menü?"),
        ScenarioTurn(user_utterance="Das ist ja nix! Wann habt ihr denn auf?"),
        ScenarioTurn(user_utterance="Und Montag? Ist doch idiotisch!"),
        ScenarioTurn(user_utterance="Na toll, und warum kein PayPal, hä?"),
        ScenarioTurn(user_utterance="Na gut, dann ist's wohl so. Tschüss."),
        ScenarioTurn(user_utterance="Auf Wiederhören!"),
    ],
    expected_tools=["ai_greeting", "get_menu", "get_date_info"],
),
AudioScenario(
    id="p3-impatient-02",
    phase="phase3",
    category="reservierung",
    description="Wechselt von Reservierung zu Frage und zurück",
    persona="impatient",
    noise_variant="clean",
    goal="Book a table for 2 for tomorrow evening at 7:30 PM. Answer all questions clearly.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "check_availability", "create_reservation"],
),
AudioScenario(
    id="p3-accent-04",
    phase="phase3",
    category="faq",
    description="Fragt nach Menü, dann nach Parken, wechselt zu Reservierung",
    persona="accent",
    noise_variant="street",
    turns=[
        ScenarioTurn(user_utterance="Hello, can you tell me das Menu?"),
        ScenarioTurn(user_utterance="Und where to park? Ich verstehe nicht..."),
        ScenarioTurn(user_utterance="Ah, okay, danke. Kann ich table reservieren? Friday evening."),
        ScenarioTurn(user_utterance="Yes, für drei, und Name is John Smith."),
        ScenarioTurn(user_utterance="Phone number? Oh, 0160 555555."),
        ScenarioTurn(user_utterance="Ja, alles klar. Bye, danke."),
    ],
    expected_tools=["ai_greeting", "get_menu", "create_reservation"],
),
AudioScenario(
    id="p3-sleepy-07",
    phase="phase3",
    category="reservierung",
    description="Langsame Reservierung, Frage stellen",
    persona="sleepy",
    noise_variant="speakerphone",
    goal="Book a table for 2 people tonight at 8 PM. Give your contact details when the agent asks.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_reservation", "get_date_info"],
),
AudioScenario(
    id="p3-impatient-08",
    phase="phase3",
    category="bestellen",
    description="Unentschlossen, von Frage zu Bestellung",
    persona="impatient",
    noise_variant="street",
    goal="Order Tteokbokki to take away. Confirm your order clearly when asked.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    caller_address="Karl-Marx-Allee 101, 10243 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_order", "verify_address"],
),
AudioScenario(
    id="p3-order-01",
    phase="phase3",
    category="order",
    description="Chaotischer Anrufer bestellt Essen",
    persona="chaos",
    noise_variant="restaurant_bg",
    goal="Order Japchae for delivery. You are in a hurry but provide all required details when asked.",
    caller_name="Stefan Bauer",
    caller_phone="+49 151 22223333",
    caller_address="Schönhauser Allee 55, 10437 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["create_order", "verify_address", "send_sms"],
),
AudioScenario(
    id="p3-faq-01",
    phase="phase3",
    category="faq",
    description="Anrufer fragt nach Menü und Verfügbarkeit",
    persona="accent",
    noise_variant="street",
    turns=[
        ScenarioTurn(user_utterance="Hallo! Ich habe eine Frage."),
        ScenarioTurn(user_utterance="What is your special dish? Uh, Ihre Spezialität?"),
        ScenarioTurn(user_utterance="Ah, okay. Can I get a table on Sunday?"),
        ScenarioTurn(user_utterance="Ähm, just two, no... three."),
        ScenarioTurn(user_utterance="Maybe 7 PM? Nein, eher 6 PM."),
        ScenarioTurn(user_utterance="Oh, by the way, do you deliver to Cologne?"),
        ScenarioTurn(user_utterance="Okay... Dann machen wir die Reservierung."),
        ScenarioTurn(user_utterance="Oh, Name ist Müller."),
        ScenarioTurn(user_utterance="Danke, bis dann!"),
    ],
    expected_tools=["check_availability", "create_reservation", "get_menu"],
),
AudioScenario(
    id="p3-reservation-01",
    phase="phase3",
    category="reservation",
    description="Impulsiver Anrufer mit spontanen Entscheidungen",
    persona="impatient",
    noise_variant="clean",
    goal="Reserve a table for 4 people this Saturday at 7 PM. Provide your name and phone when asked.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    max_turns=8,
    turns=[],
    expected_tools=["create_reservation"],
),
AudioScenario(
    id="p3-order-02",
    phase="phase3",
    category="order",
    description="Schläfriger Anrufer versucht zu bestellen",
    persona="sleepy",
    noise_variant="speakerphone",
    goal="Order Tofu Bibimbap for home delivery. Give your delivery address and contact details only when the agent asks.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    caller_address="Friedrichstr. 18, 10117 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["create_order", "verify_address", "send_sms"],
),
AudioScenario(
    id="p3-faq-02",
    phase="phase3",
    category="faq",
    description="Unzufriedener Anrufer sucht Informationen",
    persona="angry",
    noise_variant="restaurant_bg",
    turns=[
        ScenarioTurn(user_utterance="Hallo! Warum habt ihr gestern geschlossen?"),
        ScenarioTurn(user_utterance="Das hätte man irgendwo hinschreiben können!"),
        ScenarioTurn(user_utterance="Ja, wann öffnet ihr heute?"),
        ScenarioTurn(user_utterance="Und wie lange seid ihr offen?"),
        ScenarioTurn(user_utterance="Gut. Ich komme dann später vorbei. Habt ihr Parkplätze?"),
        ScenarioTurn(user_utterance="Na gut, das geht. Ich hoffe, es ist heute besser."),
        ScenarioTurn(user_utterance="Ja, ja, tschüss."),
    ],
    expected_tools=["get_date_info"],
),
AudioScenario(
    id="p3-reservation-02",
    phase="phase3",
    category="reservation",
    description="Anrufer fragt durcheinander nach Reservierung und Essen",
    persona="chaos",
    noise_variant="street",
    goal="Reserve a table for 6 people on Sunday at 1 PM. Provide name and phone number when asked.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    max_turns=8,
    turns=[],
    expected_tools=["create_reservation"],
),
AudioScenario(
    id="p3-order-03",
    phase="phase3",
    category="order",
    description="Anrufer wechselt ständig zwischen Bestellung und Fragen",
    persona="chaos",
    noise_variant="restaurant_bg",
    goal="Order Kimchi Jjigae for delivery. Be polite but brief.",
    caller_name="Stefan Bauer",
    caller_phone="+49 151 22223333",
    caller_address="Schönhauser Allee 55, 10437 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["create_order", "verify_address", "get_menu", "send_sms"],
),
AudioScenario(
    id="p3-faq-03",
    phase="phase3",
    category="faq",
    description="Anrufer mit starkem Akzent fragt mehrfach nach Menüdetails",
    persona="accent",
    noise_variant="speakerphone",
    turns=[
        ScenarioTurn(user_utterance="Hello, I have question... about menu."),
        ScenarioTurn(user_utterance="Do you have... äh, vegan options?"),
        ScenarioTurn(user_utterance="Ah, Bibimbap... What is it?"),
        ScenarioTurn(user_utterance="Okay... Can I reserve a table? No wait, what about... ähm, Ramyeon, is it spicy?"),
        ScenarioTurn(user_utterance="Oh, okay, danke. I'll think about it. Bye!"),
        ScenarioTurn(user_utterance="Ja, thank you, bye."),
    ],
    expected_tools=["get_menu"],
),
AudioScenario(
    id="p3-reservation-chaos-01",
    phase="phase3",
    category="reservation",
    description="Reservation für 3 Personen, wechselt oft Meinung",
    persona="chaos",
    noise_variant="restaurant_bg",
    goal="Book a table for 2 people tonight at 8 PM. Give your contact details when the agent asks.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "check_availability", "get_date_info", "create_reservation"],
),
AudioScenario(
    id="p3-order-impatient-02",
    phase="phase3",
    category="order",
    description="Impatient order, switches from pickup to delivery",
    persona="impatient",
    noise_variant="clean",
    goal="Order Mandu to take away. Confirm your order clearly when asked.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    caller_address="Friedrichstr. 18, 10117 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "verify_address", "create_order"],
),
AudioScenario(
    id="p3-generic-chaos-03",
    phase="phase3",
    category="general",
    description="Fragender Anrufer mit ständigen Änderungen",
    persona="chaos",
    noise_variant="street",
    goal="Order Tofu Jjigae for delivery. You are in a hurry but provide all required details when asked.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "get_menu", "get_date_info"],
),
AudioScenario(
    id="p3-delivery-accent-04",
    phase="phase3",
    category="order",
    description="Order with strong accent, changes dish",
    persona="accent",
    noise_variant="speakerphone",
    goal="Order Tofu Bibimbap for delivery. Be polite but brief.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    caller_address="Karl-Marx-Allee 101, 10243 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "verify_address", "create_order"],
),
AudioScenario(
    id="p3-faq-angry-05",
    phase="phase3",
    category="general",
    description="Frustration over parking, changes to order",
    persona="angry",
    noise_variant="restaurant_bg",
    goal="Order Bibimbap for delivery to your home address. When asked, provide your name, address, and phone number.",
    caller_name="Stefan Bauer",
    caller_phone="+49 151 22223333",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "get_menu", "create_order"],
),
AudioScenario(
    id="p3-reservation-sleepy-06",
    phase="phase3",
    category="reservation",
    description="Sleepy reservation request",
    persona="sleepy",
    noise_variant="clean",
    goal="Book a table for 2 people tonight at 8 PM. Give your contact details when the agent asks.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_reservation"],
),
AudioScenario(
    id="p3-order-chaos-07",
    phase="phase3",
    category="order",
    description="Chaotic order, switches between dishes and methods",
    persona="chaos",
    noise_variant="street",
    goal="Order Kimchi Jjigae to take away. Confirm your order clearly when asked.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    caller_address="Berliner Str. 42, 10115 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "verify_address", "create_order"],
),
AudioScenario(
    id="p3-faq-impatient-08",
    phase="phase3",
    category="general",
    description="Impatient query about payment, switches to reservation",
    persona="impatient",
    noise_variant="speakerphone",
    goal="Order Tteokbokki for delivery. You are in a hurry but provide all required details when asked.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "get_menu", "create_reservation"],
),
AudioScenario(
    id="p3-angry-02",
    phase="phase3",
    category="complaint",
    description="Anrufer beschwert sich über Lieferung und fragt nach Speisekarte",
    persona="angry",
    noise_variant="restaurant_bg",
    goal="Try to order Japchae but become frustrated with the service. Eventually request to speak to a human or escalate the issue.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "get_menu", "create_order"],
),
AudioScenario(
    id="p3-impatient-05",
    phase="phase3",
    category="faq",
    description="Ungeduldiger Anrufer fragt nach Öffnungszeiten und Bestellung.",
    persona="impatient",
    noise_variant="street",
    turns=[
        ScenarioTurn(user_utterance="Hallo, Öffnungszeiten und Bestellung, schnell!"),
        ScenarioTurn(user_utterance="Ja, Kimchi und Ramyeon, wie lange dauert das?"),
        ScenarioTurn(user_utterance="Liefern, los!"),
        ScenarioTurn(user_utterance="Ah, Friedrich-Ebert irgendwas, 69!"),
        ScenarioTurn(user_utterance="Müller... Telefonnummer?"),
        ScenarioTurn(user_utterance="0176 5432109, genug jetzt!"),
        ScenarioTurn(user_utterance="Ja, passt. Ende."),
        ScenarioTurn(user_utterance="Tschüss!"),
    ],
    expected_tools=["ai_greeting", "create_order", "verify_address", "get_date_info"],
),
AudioScenario(
    id="p3-angry-07",
    phase="phase3",
    category="complaint",
    description="Anrufer beschwert sich und fragt nach Reservierung",
    persona="angry",
    noise_variant="clean",
    goal="Try to order Tofu Jjigae but become frustrated with the service. Eventually request to speak to a human or escalate the issue.",
    caller_name="Stefan Bauer",
    caller_phone="+49 151 22223333",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_reservation"],
),
AudioScenario(
    id="p3-angry-01",
    phase="phase3",
    category="order",
    description="Anrufer ist zuerst unzufrieden mit Menüoptionen",
    persona="angry",
    noise_variant="speakerphone",
    goal="Order Tofu Bibimbap to take away. Confirm your order clearly when asked.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    caller_address="Prenzlauer Allee 12, 10405 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_order", "verify_address"],
),
AudioScenario(
    id="p3-sleepy-01",
    phase="phase3",
    category="reservation",
    description="Müder Anrufer, der sich wiederholt umentscheidet",
    persona="sleepy",
    noise_variant="clean",
    goal="Reserve a table for 6 people on Sunday at 1 PM. Provide name and phone number when asked.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_reservation", "get_date_info"],
),
AudioScenario(
    id="p3-impatient-01",
    phase="phase3",
    category="FAQ",
    description="Ungeduldiger Anrufer, fragt zu mehreren Themen",
    persona="impatient",
    noise_variant="street",
    goal="Ask about delivery areas and minimum order amounts.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "get_date_info"],
),
AudioScenario(
    id="p3-accent-01",
    phase="phase3",
    category="order",
    description="Anrufer mit starkem Akzent und Lieferverwirrung",
    persona="accent",
    noise_variant="clean",
    goal="Order Kimchi Jjigae for delivery to your home address. When asked, provide your name, address, and phone number.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    caller_address="Kastanienallee 7, 10435 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_order", "verify_address"],
),
AudioScenario(
    id="p3-faq-order-01",
    phase="phase3",
    category="faq",
    description="Fragen zu Parkplatz, dann Wechsel zu Bestellung",
    persona="impatient",
    noise_variant="street",
    turns=[
        ScenarioTurn(user_utterance="Hallo, wo kann ich parken?"),
        ScenarioTurn(user_utterance="Okay, gut. Gibt's auch Bibimbap?"),
        ScenarioTurn(user_utterance="Kann ich das JETZT bestellen? Ich habe es eilig."),
        ScenarioTurn(user_utterance="Lieferung nach Bonn, Namen Schmidt, Nummer 0151..."),
        ScenarioTurn(user_utterance="Ja, ja, das passt. Tschüss."),
    ],
    expected_tools=["ai_greeting", "get_date_info", "create_order"],
),
AudioScenario(
    id="p3-menu-reservation-01",
    phase="phase3",
    category="menu",
    description="Menüanfrage, dann Reservierung, dann FAQ",
    persona="accent",
    noise_variant="speakerphone",
    turns=[
        ScenarioTurn(user_utterance="Hallo, what do you have on menu?"),
        ScenarioTurn(user_utterance="Actually, I want to reserve a table."),
        ScenarioTurn(user_utterance="For Saturday, umm 19 Uhr?"),
        ScenarioTurn(user_utterance="Six persons, please. Oh wait, do you accept Kreditkarte?"),
        ScenarioTurn(user_utterance="Oh, that's fine, my name is Kara. Nummer is 0162..."),
        ScenarioTurn(user_utterance="Ja, genau so. Danke und goodbye."),
    ],
    expected_tools=["ai_greeting", "get_menu", "create_reservation"],
),
AudioScenario(
    id="p3-order-faq-02",
    phase="phase3",
    category="order",
    description="Bestellung mit häufigen Themenwechseln",
    persona="chaos",
    noise_variant="clean",
    goal="Order Mandu for delivery. You are in a hurry but provide all required details when asked.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    caller_address="Prenzlauer Allee 12, 10405 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "get_menu", "create_order"],
),
AudioScenario(
    id="p3-reservation-order-02",
    phase="phase3",
    category="reservation",
    description="Reservierung, dann Bestellung aber mit Unsicherheiten",
    persona="sleepy",
    noise_variant="restaurant_bg",
    goal="Book a table for 2 for tomorrow evening at 7:30 PM. Answer all questions clearly.",
    caller_name="Thomas Mueller",
    caller_phone="+49 176 12345678",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_order"],
),
AudioScenario(
    id="p3-angry-04",
    phase="phase3",
    category="complaint",
    description="Beschwerde zu Liefergebiet, dann Bestellung",
    persona="angry",
    noise_variant="speakerphone",
    goal="Try to order Tofu Bibimbap but become frustrated with the service. Eventually request to speak to a human or escalate the issue.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    max_turns=8,
    turns=[],
    expected_tools=["create_order"],
),
AudioScenario(
    id="p3-accent-05",
    phase="phase3",
    category="faq",
    description="Mit Akzent, will Infos zur Zahlung, dann reservieren",
    persona="accent",
    noise_variant="clean",
    turns=[
        ScenarioTurn(user_utterance="Hello, I have a question. Wie kann ich bezahlen?"),
        ScenarioTurn(user_utterance="Ah ok, good. Dann möchte ich Tisch reservieren... oder doch lieber bestellen? Nein, reservieren."),
        ScenarioTurn(user_utterance="Samstag, for dinner. How many? Drei Personen."),
        ScenarioTurn(user_utterance="Ja, name ist Fischer. Number 0178 456123."),
        ScenarioTurn(user_utterance="Ja, das ist richtig so. Thank you."),
    ],
    expected_tools=["create_reservation", "check_availability"],
),
AudioScenario(
    id="p3-order-001",
    phase="phase3",
    category="order",
    description="Kunde will bestellen, wechselt Gericht mehrfach",
    persona="chaos",
    noise_variant="restaurant_bg",
    goal="Order Bulgogi to take away. Confirm your order clearly when asked.",
    caller_name="Julia Hoffmann",
    caller_phone="+49 170 33334444",
    caller_address="Karl-Marx-Allee 101, 10243 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_order", "verify_address", "send_sms"],
),
AudioScenario(
    id="p3-faq-002",
    phase="phase3",
    category="faq",
    description="Anrufer fragt nach Öffnungszeiten, wechselt Anliegen",
    persona="impatient",
    noise_variant="street",
    turns=[
        ScenarioTurn(user_utterance="Hallo, reicht die Zeit für eine Reservierung heute Abend?"),
        ScenarioTurn(user_utterance="Moment, nein, wann habt ihr geöffnet?"),
        ScenarioTurn(user_utterance="Egal, was ist auf der Speisekarte? Ah, nein, wieder zurück zu den Öffnungszeiten!"),
        ScenarioTurn(user_utterance="Ach, ich komm einfach morgen vorbei. Danke. Bye."),
    ],
    expected_tools=["ai_greeting", "get_menu", "get_date_info"],
),
AudioScenario(
    id="p3-impatient-03",
    phase="phase3",
    category="reservation",
    description="Ungeduldiger Kunde wechselt mehrfach zwischen Fragen",
    persona="impatient",
    noise_variant="street",
    goal="Book a table for 2 for tomorrow evening at 7:30 PM. Answer all questions clearly.",
    caller_name="Laura Fischer",
    caller_phone="+49 172 66667777",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "check_availability", "create_reservation", "get_date_info", "end_call"],
),
AudioScenario(
    id="p3-sleepy-04",
    phase="phase3",
    category="faq",
    description="Schläfriger Kunde fragt nach Adresse und Öffnungszeiten",
    persona="sleepy",
    noise_variant="speakerphone",
    turns=[
        ScenarioTurn(user_utterance="Hallo... ähm, wo seid ihr... nochmal?"),
        ScenarioTurn(user_utterance="Und... wann habt ihr auf... bitte?"),
        ScenarioTurn(user_utterance="Hmm, war da nicht... ein Parkplatz in der Nähe...?"),
        ScenarioTurn(user_utterance="Ja... ich wollte auch... vielleicht Kimchi bestellen..."),
        ScenarioTurn(user_utterance="Aber... ich kann mich nicht entscheiden..."),
        ScenarioTurn(user_utterance="Okay, danke... ich überleg's mir noch..."),
        ScenarioTurn(user_utterance="Ja... Tschüss..."),
    ],
    expected_tools=["ai_greeting", "get_menu", "get_date_info", "end_call"],
),
AudioScenario(
    id="p3-chaos-001",
    phase="phase3",
    category="chaos",
    description="Anrufer wechselt von Bestellung zu Reservierung",
    persona="chaos",
    noise_variant="clean",
    goal="Start by asking about the menu, then order Mandu for delivery. Be indecisive but eventually commit to the order.",
    caller_name="Anna Schmidt",
    caller_phone="+49 152 98765432",
    caller_address="Friedrichstr. 18, 10117 Berlin",
    max_turns=10,
    turns=[],
    expected_tools=["ai_greeting", "get_menu", "create_order", "verify_address"],
),
AudioScenario(
    id="p3-impatient-002",
    phase="phase3",
    category="order",
    description="Unentschlossener Anrufer bestellt und fragt FAQ",
    persona="impatient",
    noise_variant="street",
    goal="Order Tofu Jjigae to take away. Confirm your order clearly when asked.",
    caller_name="Marcus Weber",
    caller_phone="+49 160 55551234",
    caller_address="Kastanienallee 7, 10435 Berlin",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "create_order", "verify_address", "get_date_info", "get_menu"],
),
AudioScenario(
    id="p3-accent-003",
    phase="phase3",
    category="faq",
    description="Anrufer sucht Infos, weicht dann zum Bestellen ab",
    persona="accent",
    noise_variant="restaurant_bg",
    turns=[
        ScenarioTurn(user_utterance="Hello, I have some Fragen about your menu."),
        ScenarioTurn(user_utterance="Do you have any vegan dishes?"),
        ScenarioTurn(user_utterance="Oh, eigentlich wollte ich auch order something."),
        ScenarioTurn(user_utterance="Wie viel kostet das Kimchi nochmal?"),
        ScenarioTurn(user_utterance="Ja, ich bestelle Kimbap und Kimchi, please."),
        ScenarioTurn(user_utterance="Address... Goetheallee 15, in Bonn."),
        ScenarioTurn(user_utterance="Ach, und was ist Tteokbokki?"),
        ScenarioTurn(user_utterance="Oh, sounds good, I'll take that too."),
        ScenarioTurn(user_utterance="Yeah, das ist es! Thank you."),
        ScenarioTurn(user_utterance="Thank you, goodbye!"),
    ],
    expected_tools=["ai_greeting", "get_menu", "create_order", "verify_address"],
),
AudioScenario(
    id="p3-sleepy-004",
    phase="phase3",
    category="reservation",
    description="Schläfriger Anrufer wechselt von Bestellung zu Reservierung und zurück",
    persona="sleepy",
    noise_variant="speakerphone",
    goal="Book a table for 2 for tomorrow evening at 7:30 PM. Answer all questions clearly.",
    caller_name="Stefan Bauer",
    caller_phone="+49 151 22223333",
    max_turns=8,
    turns=[],
    expected_tools=["ai_greeting", "check_availability", "create_reservation"],
),
AudioScenario(
    id="p3-angry-005",
    phase="phase3",
    category="faq",
    description="Anrufer ist verärgert wegen Öffnungszeiten und überlegt zu bestellen",
    persona="angry",
    noise_variant="clean",
    turns=[
        ScenarioTurn(user_utterance="Hallo! Haben Sie heute überhaupt auf?"),
        ScenarioTurn(user_utterance="Immer wieder sind Sie geschlossen!"),
        ScenarioTurn(user_utterance="Ja, okay, dann wann öffnen Sie donnerstags?"),
        ScenarioTurn(user_utterance="Na gut, ich bestelle jetzt was, Tteokbokki..."),
        ScenarioTurn(user_utterance="Nein, Moment! Haben Sie noch Bibimbap?"),
        ScenarioTurn(user_utterance="Ja, das dann, liefern Sie nach Bonn-Südstadt?"),
        ScenarioTurn(user_utterance="Gute Entscheidung, ja, genau das will ich."),
        ScenarioTurn(user_utterance="Genau, danke. Auf Wiederhören!"),
    ],
    expected_tools=["ai_greeting", "get_date_info", "create_order", "verify_address"],
),
]
